// Exemplos realistas de dados de jangadas para teste da aplicação
// Estes dados podem ser usados para popular o banco de dados ou testar formulários

export const EXEMPLOS_JANGADAS = [
  {
    // Jangada Zodiac TO SR para navio de passageiros
    numeroSerie: "ZC-2024-001-LIS",
    marca: "Zodiac",
    modelo: "TO SR",
    tipo: "Balsa Salva-Vidas",
    capacidade: 25,
    tipoPack: "Pack SOLAS A",
    // Novos campos adicionados - Sistema THANNER, Válvulas OTS65
    lotacao: 25,
    hru: "HRU-ZC-2024-001",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 25 },
      "Rações de Emergência": { incluido: true, quantidade: 25 },
      "Água Potável": { incluido: true, quantidade: 37.5 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Comprimidos para o Enjoo": { incluido: true, quantidade: 150 },
      "Sacos para Enjoo": { incluido: true, quantidade: 25 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Fachos de Mão": { incluido: true, quantidade: 6 },
      "Sinais Flutuantes de Fumo": { incluido: true, quantidade: 2 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Heliógrafo (Espelho de Sinais)": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Esponjas": { incluido: true, quantidade: 2 },
      "Abre-latas": { incluido: true, quantidade: 3 },
      "Copos Graduados": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 2 },
      "Kit de Pesca": { incluido: true, quantidade: 1 },
      "Manual de Sobrevivência": { incluido: true, quantidade: 1 },
      "Tabela de Sinais de Salvamento": { incluido: true, quantidade: 1 },
      "Fole ou Bomba de Enchimento": { incluido: true, quantidade: 1 },
      "Tampões para Furos": { incluido: true, quantidade: 5 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 2 }
    },
    validadeComponentes: {
      "Balsa Inflável": "12/2029",
      "Coletes Salva-Vidas": "06/2028",
      "Rações de Emergência": "09/2026",
      "Água Potável": "09/2026",
      "Kit de Primeiros Socorros": "03/2027",
      "Comprimidos para o Enjoo": "03/2027",
      "Sacos para Enjoo": "03/2027",
      "Foguetes com Paraquedas": "11/2026",
      "Fachos de Mão": "11/2026",
      "Sinais Flutuantes de Fumo": "11/2026",
      "Lanterna Estanque": "04/2027",
      "Heliógrafo (Espelho de Sinais)": "12/2030",
      "Apito": "12/2030",
      "Faca de Ponta Redonda Flutuante": "12/2030",
      "Esponjas": "12/2030",
      "Abre-latas": "12/2030",
      "Copos Graduados": "12/2030",
      "Manta Térmica": "07/2027",
      "Kit de Pesca": "12/2030",
      "Manual de Sobrevivência": "12/2030",
      "Tabela de Sinais de Salvamento": "12/2030",
      "Fole ou Bomba de Enchimento": "12/2030",
      "Tampões para Furos": "12/2030",
      "Kit de Reparação": "12/2030",
      "Âncora Flutuante (Drogue)": "12/2030"
    },
    dataFabricacao: new Date("2024-03-15"),
    dataInspecao: new Date("2024-09-10"),
    dataProximaInspecao: new Date("2025-09-10"),
    status: "ativo",
    tecnico: "João Silva",
    cilindroNumeroSerie: "CO2-ZC-2024-001",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 25,
    cilindroTara: 15.2,
    cilindroPesoBruto: 26.51,
    cilindroQuantidadeCO2: 10.77,
    cilindroQuantidadeN2: 0.54,
    cilindroTesteHidraulico: new Date("2024-06-15"),
    cilindroProximoTesteHidraulico: new Date("2029-06-15"),
    cilindroValidade: "03/2029"
  },

  {
    // Jangada RFD Surviva MKIII para navio cargueiro - Sistema THANNER, Válvulas OTS65
    numeroSerie: "RFD-2023-045-OPO",
    marca: "RFD",
    modelo: "Surviva MKIII",
    tipo: "Balsa Salva-Vidas",
    capacidade: 25,
    tipoPack: "Pack SOLAS B",
    // Novos campos adicionados
    lotacao: 25,
    hru: "HRU-RFD-2023-045",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 25 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Comprimidos para o Enjoo": { incluido: true, quantidade: 150 },
      "Sacos para Enjoo": { incluido: true, quantidade: 25 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 2 },
      "Fachos de Mão": { incluido: true, quantidade: 3 },
      "Sinais Flutuantes de Fumo": { incluido: true, quantidade: 1 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Heliógrafo (Espelho de Sinais)": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Esponjas": { incluido: true, quantidade: 2 },
      "Manta Térmica": { incluido: true, quantidade: 2 },
      "Manual de Sobrevivência": { incluido: true, quantidade: 1 },
      "Tabela de Sinais de Salvamento": { incluido: true, quantidade: 1 },
      "Fole ou Bomba de Enchimento": { incluido: true, quantidade: 1 },
      "Tampões para Furos": { incluido: true, quantidade: 5 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 2 }
    },
    validadeComponentes: {
      "Balsa Inflável": "11/2028",
      "Coletes Salva-Vidas": "05/2027",
      "Kit de Primeiros Socorros": "02/2026",
      "Comprimidos para o Enjoo": "02/2026",
      "Sacos para Enjoo": "02/2026",
      "Foguetes com Paraquedas": "10/2025",
      "Fachos de Mão": "10/2025",
      "Sinais Flutuantes de Fumo": "10/2025",
      "Lanterna Estanque": "03/2026",
      "Heliógrafo (Espelho de Sinais)": "11/2029",
      "Apito": "11/2029",
      "Faca de Ponta Redonda Flutuante": "11/2029",
      "Esponjas": "11/2029",
      "Manta Térmica": "06/2026",
      "Manual de Sobrevivência": "11/2029",
      "Tabela de Sinais de Salvamento": "11/2029",
      "Fole ou Bomba de Enchimento": "11/2029",
      "Tampões para Furos": "11/2029",
      "Kit de Reparação": "11/2029",
      "Âncora Flutuante (Drogue)": "11/2029"
    },
    dataFabricacao: new Date("2023-08-22"),
    dataInspecao: new Date("2024-02-15"),
    dataProximaInspecao: new Date("2025-02-15"),
    status: "ativo",
    tecnico: "Maria Santos",
    cilindroNumeroSerie: "CO2-RFD-2023-045",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 25,
    cilindroTara: 15.2,
    cilindroPesoBruto: 28.4,
    cilindroQuantidadeCO2: 12.57,
    cilindroQuantidadeN2: 0.63,
    cilindroTesteHidraulico: new Date("2023-11-20"),
    cilindroProximoTesteHidraulico: new Date("2028-11-20"),
    cilindroValidade: "08/2028"
  },

  {
    // Jangada Zodiac Coaster para barco de pesca - Capacidade 8P: 3.68kg CO2, 0.235kg N2
    numeroSerie: "ZC-2022-112-FAO",
    marca: "Zodiac",
    modelo: "Coaster",
    tipo: "Balsa Salva-Vidas",
    capacidade: 8,
    tipoPack: "Pack Coastal",
    // Novos campos adicionados
    lotacao: 8,
    hru: "HRU-ZC-2022-112",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 8 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 2 },
      "Fachos de Mão": { incluido: true, quantidade: 2 },
      "Sinais Flutuantes de Fumo": { incluido: true, quantidade: 1 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "09/2027",
      "Coletes Salva-Vidas": "03/2026",
      "Foguetes com Paraquedas": "08/2024",
      "Fachos de Mão": "08/2024",
      "Sinais Flutuantes de Fumo": "08/2024",
      "Lanterna Estanque": "01/2025",
      "Faca de Ponta Redonda Flutuante": "09/2028",
      "Kit de Reparação": "09/2028",
      "Âncora Flutuante (Drogue)": "09/2028"
    },
    dataFabricacao: new Date("2022-11-30"),
    dataInspecao: new Date("2024-05-20"),
    dataProximaInspecao: new Date("2025-05-20"),
    status: "manutencao",
    tecnico: "Carlos Oliveira",
    cilindroNumeroSerie: "CO2-ZC-2022-112",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "GIST",
    cilindroCapacidade: 8,
    cilindroTara: 8.5,
    cilindroPesoBruto: 12.415,
    cilindroQuantidadeCO2: 3.68,
    cilindroQuantidadeN2: 0.235,
    cilindroTesteHidraulico: new Date("2022-09-10"),
    cilindroProximoTesteHidraulico: new Date("2027-09-10"),
    cilindroValidade: "11/2027"
  },

  {
    // Jangada Zodiac TO para embarcação comercial - Capacidade 16P: 7.18kg CO2, 0.36kg N2
    numeroSerie: "ZC-2023-089-LEI",
    marca: "Zodiac",
    modelo: "TO",
    tipo: "Balsa Salva-Vidas",
    capacidade: 16,
    tipoPack: "Pack SOLAS A",
    // Sistema THANNER, Válvulas OTS65
    lotacao: 16,
    hru: "HRU-ZC-2023-089",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 16 },
      "Rações de Emergência": { incluido: true, quantidade: 16 },
      "Água Potável": { incluido: true, quantidade: 24 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 2 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "10/2028",
      "Coletes Salva-Vidas": "04/2027",
      "Rações de Emergência": "07/2026",
      "Água Potável": "07/2026",
      "Kit de Primeiros Socorros": "01/2027",
      "Foguetes com Paraquedas": "09/2025",
      "Lanterna Estanque": "02/2026",
      "Apito": "10/2029",
      "Faca de Ponta Redonda Flutuante": "10/2029",
      "Manta Térmica": "05/2026",
      "Kit de Reparação": "10/2029",
      "Âncora Flutuante (Drogue)": "10/2029"
    },
    dataFabricacao: new Date("2023-12-10"),
    dataInspecao: new Date("2024-06-15"),
    dataProximaInspecao: new Date("2025-06-15"),
    status: "ativo",
    tecnico: "Ana Costa",
    cilindroNumeroSerie: "CO2-ZC-2023-089",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 16,
    cilindroTara: 12.8,
    cilindroPesoBruto: 20.74,
    cilindroQuantidadeCO2: 7.18,
    cilindroQuantidadeN2: 0.36,
    cilindroTesteHidraulico: new Date("2023-10-05"),
    cilindroProximoTesteHidraulico: new Date("2028-10-05"),
    cilindroValidade: "12/2028"
  },

  {
    // Jangada Zodiac MOR para navio offshore - Capacidade 10P: 13.2kg CO2, 0.792kg N2
    numeroSerie: "ZC-2024-156-AVE",
    marca: "Zodiac",
    modelo: "MOR",
    tipo: "Balsa Salva-Vidas",
    capacidade: 10,
    tipoPack: "Pack SOLAS A",
    // Sistema THANNER, Válvulas OTS65
    lotacao: 10,
    hru: "HRU-ZC-2024-156",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 10 },
      "Rações de Emergência": { incluido: true, quantidade: 10 },
      "Água Potável": { incluido: true, quantidade: 15 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "11/2029",
      "Coletes Salva-Vidas": "05/2028",
      "Rações de Emergência": "08/2026",
      "Água Potável": "08/2026",
      "Kit de Primeiros Socorros": "02/2027",
      "Foguetes com Paraquedas": "10/2026",
      "Lanterna Estanque": "03/2027",
      "Apito": "11/2030",
      "Faca de Ponta Redonda Flutuante": "11/2030",
      "Manta Térmica": "06/2027",
      "Kit de Reparação": "11/2030",
      "Âncora Flutuante (Drogue)": "11/2030"
    },
    dataFabricacao: new Date("2024-01-20"),
    dataInspecao: new Date("2024-07-25"),
    dataProximaInspecao: new Date("2025-07-25"),
    status: "ativo",
    tecnico: "Pedro Alves",
    cilindroNumeroSerie: "CO2-ZC-2024-156",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 10,
    cilindroTara: 18.5,
    cilindroPesoBruto: 32.492,
    cilindroQuantidadeCO2: 13.2,
    cilindroQuantidadeN2: 0.792,
    cilindroTesteHidraulico: new Date("2024-04-15"),
    cilindroProximoTesteHidraulico: new Date("2029-04-15"),
    cilindroValidade: "01/2029"
  },

  {
    // Jangada RFD Seasava Plus - Sistema Thanner, Válvulas OTS65, A10, A6, C7, D7, A5, A7
    numeroSerie: "RFD-2024-078-POR",
    marca: "RFD",
    modelo: "Seasava Plus",
    tipo: "Balsa Salva-Vidas",
    capacidade: 20,
    tipoPack: "Pack SOLAS A",
    // Sistema THANNER, múltiplas válvulas
    lotacao: 20,
    hru: "HRU-RFD-2024-078",
    tubosAltaPressao: 1,
    valvulasAlivio: 7,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 20 },
      "Rações de Emergência": { incluido: true, quantidade: 20 },
      "Água Potável": { incluido: true, quantidade: 30 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 2 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "12/2029",
      "Coletes Salva-Vidas": "06/2028",
      "Rações de Emergência": "09/2026",
      "Água Potável": "09/2026",
      "Kit de Primeiros Socorros": "03/2027",
      "Foguetes com Paraquedas": "11/2026",
      "Lanterna Estanque": "04/2027",
      "Apito": "12/2030",
      "Faca de Ponta Redonda Flutuante": "12/2030",
      "Manta Térmica": "07/2027",
      "Kit de Reparação": "12/2030",
      "Âncora Flutuante (Drogue)": "12/2030"
    },
    dataFabricacao: new Date("2024-02-28"),
    dataInspecao: new Date("2024-08-30"),
    dataProximaInspecao: new Date("2025-08-30"),
    status: "ativo",
    tecnico: "Sofia Rodrigues",
    cilindroNumeroSerie: "CO2-RFD-2024-078",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 20,
    cilindroTara: 14.2,
    cilindroPesoBruto: 25.0,
    cilindroQuantidadeCO2: 9.38,
    cilindroQuantidadeN2: 0.62,
    cilindroTesteHidraulico: new Date("2024-05-20"),
    cilindroProximoTesteHidraulico: new Date("2029-05-20"),
    cilindroValidade: "02/2029"
  },

  {
    // Jangada RFD Surviva MKII - Sistema VTE99, Válvulas Supernova, Packs SOLAS A/B
    numeroSerie: "RFD-2023-112-LIS",
    marca: "RFD",
    modelo: "Surviva MKII",
    tipo: "Balsa Salva-Vidas",
    capacidade: 12,
    tipoPack: "Pack SOLAS A",
    // Sistema VTE99, Válvulas Supernova, Iluminação LGT-RL5
    lotacao: 12,
    hru: "HRU-RFD-2023-112",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 12 },
      "Rações de Emergência": { incluido: true, quantidade: 12 },
      "Água Potável": { incluido: true, quantidade: 18 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "10/2028",
      "Coletes Salva-Vidas": "04/2027",
      "Rações de Emergência": "07/2026",
      "Água Potável": "07/2026",
      "Kit de Primeiros Socorros": "01/2027",
      "Foguetes com Paraquedas": "09/2025",
      "Lanterna Estanque": "02/2026",
      "Apito": "10/2029",
      "Faca de Ponta Redonda Flutuante": "10/2029",
      "Manta Térmica": "05/2026",
      "Kit de Reparação": "10/2029",
      "Âncora Flutuante (Drogue)": "10/2029"
    },
    dataFabricacao: new Date("2023-11-15"),
    dataInspecao: new Date("2024-05-20"),
    dataProximaInspecao: new Date("2025-05-20"),
    status: "ativo",
    tecnico: "Miguel Ferreira",
    cilindroNumeroSerie: "CO2-RFD-2023-112",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "VTE99",
    cilindroCapacidade: 12,
    cilindroTara: 9.8,
    cilindroPesoBruto: 15.0,
    cilindroQuantidadeCO2: 4.17,
    cilindroQuantidadeN2: 0.27,
    cilindroTesteHidraulico: new Date("2023-09-10"),
    cilindroProximoTesteHidraulico: new Date("2028-09-10"),
    cilindroValidade: "11/2028"
  },

  {
    // Jangada RFD Surviva MKIV TO - Sistema Leafield, Válvulas A10, A6, C7, D7, A5, A7
    numeroSerie: "RFD-2024-203-SET",
    marca: "RFD",
    modelo: "Surviva MKIV TO",
    tipo: "Balsa Salva-Vidas",
    capacidade: 8,
    tipoPack: "Pack SOLAS A",
    // Sistema Leafield, múltiplas válvulas, Iluminação SURV-L-INT-01/EXT-02, Bateria SURV-BATT-LITH-01
    lotacao: 8,
    hru: "HRU-RFD-2024-203",
    tubosAltaPressao: 1,
    valvulasAlivio: 6,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 8 },
      "Rações de Emergência": { incluido: true, quantidade: 8 },
      "Água Potável": { incluido: true, quantidade: 12 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "01/2030",
      "Coletes Salva-Vidas": "07/2028",
      "Rações de Emergência": "10/2026",
      "Água Potável": "10/2026",
      "Kit de Primeiros Socorros": "04/2027",
      "Foguetes com Paraquedas": "12/2026",
      "Lanterna Estanque": "05/2027",
      "Apito": "01/2031",
      "Faca de Ponta Redonda Flutuante": "01/2031",
      "Manta Térmica": "08/2027",
      "Kit de Reparação": "01/2031",
      "Âncora Flutuante (Drogue)": "01/2031"
    },
    dataFabricacao: new Date("2024-03-10"),
    dataInspecao: new Date("2024-09-15"),
    dataProximaInspecao: new Date("2025-09-15"),
    status: "ativo",
    tecnico: "Teresa Gomes",
    cilindroNumeroSerie: "CO2-RFD-2024-203",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "LEAFIELD",
    cilindroCapacidade: 8,
    cilindroTara: 8.2,
    cilindroPesoBruto: 12.0,
    cilindroQuantidadeCO2: 3.51,
    cilindroQuantidadeN2: 0.23,
    cilindroTesteHidraulico: new Date("2024-06-05"),
    cilindroProximoTesteHidraulico: new Date("2029-06-05"),
    cilindroValidade: "03/2029"
  },

  {
    // Jangada DSB LR97 - Sistema THANNER, Válvulas OTS65
    numeroSerie: "DSB-2023-067-FAR",
    marca: "DSB",
    modelo: "LR97",
    tipo: "Balsa Salva-Vidas",
    capacidade: 15,
    tipoPack: "Pack SOLAS A",
    // Sistema THANNER, Válvulas OTS65
    lotacao: 15,
    hru: "HRU-DSB-2023-067",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 15 },
      "Rações de Emergência": { incluido: true, quantidade: 15 },
      "Água Potável": { incluido: true, quantidade: 22.5 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 2 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "08/2028",
      "Coletes Salva-Vidas": "02/2027",
      "Rações de Emergência": "05/2026",
      "Água Potável": "05/2026",
      "Kit de Primeiros Socorros": "11/2026",
      "Foguetes com Paraquedas": "07/2025",
      "Lanterna Estanque": "12/2025",
      "Apito": "08/2029",
      "Faca de Ponta Redonda Flutuante": "08/2029",
      "Manta Térmica": "03/2026",
      "Kit de Reparação": "08/2029",
      "Âncora Flutuante (Drogue)": "08/2029"
    },
    dataFabricacao: new Date("2023-10-05"),
    dataInspecao: new Date("2024-04-10"),
    dataProximaInspecao: new Date("2025-04-10"),
    status: "ativo",
    tecnico: "João Martins",
    cilindroNumeroSerie: "CO2-DSB-2023-067",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "THANNER",
    cilindroCapacidade: 15,
    cilindroTara: 11.5,
    cilindroPesoBruto: 20.0,
    cilindroQuantidadeCO2: 7.5,
    cilindroQuantidadeN2: 0.45,
    cilindroTesteHidraulico: new Date("2023-08-01"),
    cilindroProximoTesteHidraulico: new Date("2028-08-01"),
    cilindroValidade: "10/2028"
  },

  {
    // Jangada Lalizas ISO-RAFT - Sistema HSR-OH-III, Válvulas AQF-5-100, 71891
    numeroSerie: "LAL-2024-034-ATH",
    marca: "Lalizas",
    modelo: "ISO-RAFT",
    tipo: "Balsa Salva-Vidas",
    capacidade: 10,
    tipoPack: "Pack ISO 9650-1",
    // Sistema HSR-OH-III, Válvulas AQF-5-100, 71891
    lotacao: 10,
    hru: "HRU-LAL-2024-034",
    tubosAltaPressao: 1,
    valvulasAlivio: 2,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 10 },
      "Rações de Emergência": { incluido: true, quantidade: 10 },
      "Água Potável": { incluido: true, quantidade: 15 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "09/2029",
      "Coletes Salva-Vidas": "03/2028",
      "Rações de Emergência": "06/2026",
      "Água Potável": "06/2026",
      "Kit de Primeiros Socorros": "12/2026",
      "Foguetes com Paraquedas": "08/2026",
      "Lanterna Estanque": "01/2027",
      "Apito": "09/2030",
      "Faca de Ponta Redonda Flutuante": "09/2030",
      "Manta Térmica": "04/2027",
      "Kit de Reparação": "09/2030",
      "Âncora Flutuante (Drogue)": "09/2030"
    },
    dataFabricacao: new Date("2024-04-15"),
    dataInspecao: new Date("2024-10-20"),
    dataProximaInspecao: new Date("2025-10-20"),
    status: "ativo",
    tecnico: "Dimitris Papadopoulos",
    cilindroNumeroSerie: "CO2-LAL-2024-034",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "HSR-OH-III",
    cilindroCapacidade: 10,
    cilindroTara: 9.0,
    cilindroPesoBruto: 14.0,
    cilindroQuantidadeCO2: 4.0,
    cilindroQuantidadeN2: 0.25,
    cilindroTesteHidraulico: new Date("2024-07-10"),
    cilindroProximoTesteHidraulico: new Date("2029-07-10"),
    cilindroValidade: "04/2029"
  },

  {
    // Jangada Plastimo Cruiser - Packs Cruiser Standard/ORC
    numeroSerie: "PLA-2023-089-BRE",
    marca: "Plastimo",
    modelo: "Cruiser",
    tipo: "Balsa Salva-Vidas",
    capacidade: 6,
    tipoPack: "Pack Cruiser Standard",
    // Packs Cruiser Standard, Cruiser ORC
    lotacao: 6,
    hru: "HRU-PLA-2023-089",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 6 },
      "Rações de Emergência": { incluido: true, quantidade: 6 },
      "Água Potável": { incluido: true, quantidade: 9 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "07/2028",
      "Coletes Salva-Vidas": "01/2027",
      "Rações de Emergência": "04/2026",
      "Água Potável": "04/2026",
      "Kit de Primeiros Socorros": "10/2026",
      "Foguetes com Paraquedas": "06/2025",
      "Lanterna Estanque": "11/2025",
      "Apito": "07/2029",
      "Faca de Ponta Redonda Flutuante": "07/2029",
      "Manta Térmica": "02/2026",
      "Kit de Reparação": "07/2029",
      "Âncora Flutuante (Drogue)": "07/2029"
    },
    dataFabricacao: new Date("2023-09-20"),
    dataInspecao: new Date("2024-03-25"),
    dataProximaInspecao: new Date("2025-03-25"),
    status: "ativo",
    tecnico: "Marie Dubois",
    cilindroNumeroSerie: "CO2-PLA-2023-089",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "STANDARD",
    cilindroCapacidade: 6,
    cilindroTara: 6.5,
    cilindroPesoBruto: 9.0,
    cilindroQuantidadeCO2: 2.2,
    cilindroQuantidadeN2: 0.14,
    cilindroTesteHidraulico: new Date("2023-07-15"),
    cilindroProximoTesteHidraulico: new Date("2028-07-15"),
    cilindroValidade: "09/2028"
  },

  {
    // Jangada Sea-Safe Pro-Light - Sistema NSS
    numeroSerie: "SEA-2024-145-SYD",
    marca: "Sea-Safe",
    modelo: "Pro-Light",
    tipo: "Balsa Salva-Vidas",
    capacidade: 8,
    tipoPack: "Pack ISO 9650-1",
    // Sistema NSS
    lotacao: 8,
    hru: "HRU-SEA-2024-145",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 8 },
      "Rações de Emergência": { incluido: true, quantidade: 8 },
      "Água Potável": { incluido: true, quantidade: 12 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "11/2029",
      "Coletes Salva-Vidas": "05/2028",
      "Rações de Emergência": "08/2026",
      "Água Potável": "08/2026",
      "Kit de Primeiros Socorros": "02/2027",
      "Foguetes com Paraquedas": "10/2026",
      "Lanterna Estanque": "03/2027",
      "Apito": "11/2030",
      "Faca de Ponta Redonda Flutuante": "11/2030",
      "Manta Térmica": "06/2027",
      "Kit de Reparação": "11/2030",
      "Âncora Flutuante (Drogue)": "11/2030"
    },
    dataFabricacao: new Date("2024-05-10"),
    dataInspecao: new Date("2024-11-15"),
    dataProximaInspecao: new Date("2025-11-15"),
    status: "ativo",
    tecnico: "James Wilson",
    cilindroNumeroSerie: "CO2-SEA-2024-145",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "NSS",
    cilindroCapacidade: 8,
    cilindroTara: 7.2,
    cilindroPesoBruto: 10.0,
    cilindroQuantidadeCO2: 2.4,
    cilindroQuantidadeN2: 0.15,
    cilindroTesteHidraulico: new Date("2024-08-05"),
    cilindroProximoTesteHidraulico: new Date("2029-08-05"),
    cilindroValidade: "05/2029"
  },

  {
    // Jangada Eurovinil Leisure Syntesy - Pack Coastal
    numeroSerie: "EUR-2023-056-MAD",
    marca: "Eurovinil",
    modelo: "Leisure Syntesy",
    tipo: "Balsa Salva-Vidas",
    capacidade: 8,
    tipoPack: "Pack Coastal",
    // Pack Coastal
    lotacao: 8,
    hru: "HRU-EUR-2023-056",
    tubosAltaPressao: 1,
    valvulasAlivio: 1,
    valvulasInsuflacao: 1,
    bateriaLitio: 1,
    luzExterior: 1,
    componentesSelecionados: {
      "Balsa Inflável": { incluido: true, quantidade: 1 },
      "Coletes Salva-Vidas": { incluido: true, quantidade: 8 },
      "Rações de Emergência": { incluido: true, quantidade: 8 },
      "Água Potável": { incluido: true, quantidade: 12 },
      "Kit de Primeiros Socorros": { incluido: true, quantidade: 1 },
      "Foguetes com Paraquedas": { incluido: true, quantidade: 4 },
      "Lanterna Estanque": { incluido: true, quantidade: 1 },
      "Apito": { incluido: true, quantidade: 1 },
      "Faca de Ponta Redonda Flutuante": { incluido: true, quantidade: 1 },
      "Manta Térmica": { incluido: true, quantidade: 1 },
      "Kit de Reparação": { incluido: true, quantidade: 1 },
      "Âncora Flutuante (Drogue)": { incluido: true, quantidade: 1 }
    },
    validadeComponentes: {
      "Balsa Inflável": "06/2028",
      "Coletes Salva-Vidas": "12/2026",
      "Rações de Emergência": "03/2026",
      "Água Potável": "03/2026",
      "Kit de Primeiros Socorros": "09/2026",
      "Foguetes com Paraquedas": "05/2025",
      "Lanterna Estanque": "10/2025",
      "Apito": "06/2029",
      "Faca de Ponta Redonda Flutuante": "06/2029",
      "Manta Térmica": "01/2026",
      "Kit de Reparação": "06/2029",
      "Âncora Flutuante (Drogue)": "06/2029"
    },
    dataFabricacao: new Date("2023-08-30"),
    dataInspecao: new Date("2024-02-28"),
    dataProximaInspecao: new Date("2025-02-28"),
    status: "ativo",
    tecnico: "Carlos Rodriguez",
    cilindroNumeroSerie: "CO2-EUR-2023-056",
    cilindroTipo: "CO2+N2",
    cilindroSistema: "COASTAL",
    cilindroCapacidade: 8,
    cilindroTara: 7.8,
    cilindroPesoBruto: 11.0,
    cilindroQuantidadeCO2: 2.7,
    cilindroQuantidadeN2: 0.17,
    cilindroTesteHidraulico: new Date("2023-06-25"),
    cilindroProximoTesteHidraulico: new Date("2028-06-25"),
    cilindroValidade: "08/2028"
  }
];

// Função utilitária para obter um exemplo aleatório
export function getExemploJangadaAleatorio() {
  const indice = Math.floor(Math.random() * EXEMPLOS_JANGADAS.length);
  return EXEMPLOS_JANGADAS[indice];
}

// Função para obter todos os exemplos
export function getTodosExemplosJangadas() {
  return EXEMPLOS_JANGADAS;
}