
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ClienteScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  telefone: 'telefone',
  endereco: 'endereco',
  nif: 'nif',
  tipo: 'tipo',
  delegacao: 'delegacao',
  tecnico: 'tecnico',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NavioScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  matricula: 'matricula',
  imo: 'imo',
  mmsi: 'mmsi',
  callSign: 'callSign',
  bandeira: 'bandeira',
  comprimento: 'comprimento',
  largura: 'largura',
  calado: 'calado',
  capacidade: 'capacidade',
  anoConstrucao: 'anoConstrucao',
  status: 'status',
  dataInspecao: 'dataInspecao',
  dataProximaInspecao: 'dataProximaInspecao',
  clienteId: 'clienteId',
  proprietarioId: 'proprietarioId',
  delegacao: 'delegacao',
  ilha: 'ilha',
  tecnico: 'tecnico',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JangadaScalarFieldEnum = {
  id: 'id',
  numeroSerie: 'numeroSerie',
  marcaId: 'marcaId',
  modeloId: 'modeloId',
  lotacaoId: 'lotacaoId',
  tipoPackId: 'tipoPackId',
  tipo: 'tipo',
  tipoPack: 'tipoPack',
  itensTipoPack: 'itensTipoPack',
  dataFabricacao: 'dataFabricacao',
  dataInspecao: 'dataInspecao',
  dataProximaInspecao: 'dataProximaInspecao',
  capacidade: 'capacidade',
  peso: 'peso',
  dimensoes: 'dimensoes',
  numeroAprovacao: 'numeroAprovacao',
  status: 'status',
  estado: 'estado',
  clienteId: 'clienteId',
  proprietarioId: 'proprietarioId',
  navioId: 'navioId',
  tecnico: 'tecnico',
  hruAplicavel: 'hruAplicavel',
  hruNumeroSerie: 'hruNumeroSerie',
  hruModelo: 'hruModelo',
  hruDataInstalacao: 'hruDataInstalacao',
  hruDataValidade: 'hruDataValidade',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProprietarioScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  telefone: 'telefone',
  endereco: 'endereco',
  nif: 'nif',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PessoaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  telefone: 'telefone',
  cargo: 'cargo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CertificadoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  numero: 'numero',
  dataEmissao: 'dataEmissao',
  dataValidade: 'dataValidade',
  entidadeEmissora: 'entidadeEmissora',
  status: 'status',
  filePath: 'filePath',
  notas: 'notas',
  clienteId: 'clienteId',
  navioId: 'navioId',
  jangadaId: 'jangadaId',
  obraId: 'obraId',
  inspecaoId: 'inspecaoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  descricao: 'descricao',
  categoria: 'categoria',
  quantidade: 'quantidade',
  quantidadeMinima: 'quantidadeMinima',
  precoUnitario: 'precoUnitario',
  fornecedor: 'fornecedor',
  localizacao: 'localizacao',
  refOrey: 'refOrey',
  refFabricante: 'refFabricante',
  lote: 'lote',
  codigoBarra: 'codigoBarra',
  dataValidade: 'dataValidade',
  imagem: 'imagem',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MovimentacaoStockScalarFieldEnum = {
  id: 'id',
  stockId: 'stockId',
  tipo: 'tipo',
  quantidade: 'quantidade',
  motivo: 'motivo',
  data: 'data',
  responsavel: 'responsavel'
};

exports.Prisma.CilindroScalarFieldEnum = {
  id: 'id',
  numeroSerie: 'numeroSerie',
  tipo: 'tipo',
  sistemaId: 'sistemaId',
  tipoCilindroId: 'tipoCilindroId',
  tipoValvulaId: 'tipoValvulaId',
  capacidade: 'capacidade',
  capacidadeN2: 'capacidadeN2',
  tara: 'tara',
  pesoBruto: 'pesoBruto',
  dataFabricacao: 'dataFabricacao',
  dataTeste: 'dataTeste',
  dataProximoTeste: 'dataProximoTeste',
  status: 'status',
  pressaoTrabalho: 'pressaoTrabalho',
  pressaoTeste: 'pressaoTeste',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgendamentoScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  descricao: 'descricao',
  dataInicio: 'dataInicio',
  dataFim: 'dataFim',
  tipo: 'tipo',
  status: 'status',
  prioridade: 'prioridade',
  navioId: 'navioId',
  jangadaId: 'jangadaId',
  cilindroId: 'cilindroId',
  pessoaId: 'pessoaId',
  responsavel: 'responsavel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FaturaScalarFieldEnum = {
  id: 'id',
  numero: 'numero',
  dataEmissao: 'dataEmissao',
  dataVencimento: 'dataVencimento',
  valor: 'valor',
  status: 'status',
  descricao: 'descricao',
  clienteId: 'clienteId',
  navioId: 'navioId',
  jangadaId: 'jangadaId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificacaoScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  mensagem: 'mensagem',
  tipo: 'tipo',
  lida: 'lida',
  clienteId: 'clienteId',
  navioId: 'navioId',
  jangadaId: 'jangadaId',
  cilindroId: 'cilindroId',
  dataEnvio: 'dataEnvio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PartnerScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  email: 'email',
  telefone: 'telefone',
  endereco: 'endereco',
  nif: 'nif',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ObraScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  titulo: 'titulo',
  descricao: 'descricao',
  tipo: 'tipo',
  status: 'status',
  dataInicio: 'dataInicio',
  dataFim: 'dataFim',
  orcamento: 'orcamento',
  filePath: 'filePath',
  clienteId: 'clienteId',
  jangadaId: 'jangadaId',
  inspecaoId: 'inspecaoId',
  responsavel: 'responsavel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PredictiveMaintenanceScalarFieldEnum = {
  id: 'id',
  equipamentoId: 'equipamentoId',
  tipoEquipamento: 'tipoEquipamento',
  tipoManutencao: 'tipoManutencao',
  probabilidade: 'probabilidade',
  severidade: 'severidade',
  dataPrevista: 'dataPrevista',
  recomendacao: 'recomendacao',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RelatorioScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  tipo: 'tipo',
  periodoInicio: 'periodoInicio',
  periodoFim: 'periodoFim',
  dados: 'dados',
  criadoPor: 'criadoPor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InspecaoScalarFieldEnum = {
  id: 'id',
  numero: 'numero',
  numeroSerieJangada: 'numeroSerieJangada',
  tipoInspecao: 'tipoInspecao',
  dataInspecao: 'dataInspecao',
  dataProxima: 'dataProxima',
  resultado: 'resultado',
  status: 'status',
  tecnico: 'tecnico',
  observacoes: 'observacoes',
  filePath: 'filePath',
  navioId: 'navioId',
  jangadaId: 'jangadaId',
  cilindroId: 'cilindroId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustoInspecaoScalarFieldEnum = {
  id: 'id',
  valor: 'valor',
  descricao: 'descricao',
  tipo: 'tipo',
  quantidade: 'quantidade',
  responsavel: 'responsavel',
  inspecaoId: 'inspecaoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HistoricoInspecaoScalarFieldEnum = {
  id: 'id',
  dataRealizada: 'dataRealizada',
  descricao: 'descricao',
  resultado: 'resultado',
  tecnico: 'tecnico',
  observacoes: 'observacoes',
  custo: 'custo',
  dataPreviaProxima: 'dataPreviaProxima',
  inspecaoId: 'inspecaoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InspecaoComponenteScalarFieldEnum = {
  id: 'id',
  jangadaId: 'jangadaId',
  nome: 'nome',
  quantidade: 'quantidade',
  estado: 'estado',
  validade: 'validade',
  tipo: 'tipo',
  notas: 'notas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubstituicaoComponenteScalarFieldEnum = {
  id: 'id',
  componenteNome: 'componenteNome',
  quantidade: 'quantidade',
  motivoSubstituicao: 'motivoSubstituicao',
  dataSubstituicao: 'dataSubstituicao',
  inspecaoId: 'inspecaoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MarcaJangadaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ModeloJangadaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  marcaId: 'marcaId',
  sistemaInsuflacao: 'sistemaInsuflacao',
  valvulasPadrao: 'valvulasPadrao',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ModeloJangadaItemScalarFieldEnum = {
  id: 'id',
  modeloId: 'modeloId',
  stockId: 'stockId',
  quantidade: 'quantidade',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LotacaoJangadaScalarFieldEnum = {
  id: 'id',
  capacidade: 'capacidade',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EspecificacaoTecnicaScalarFieldEnum = {
  id: 'id',
  marcaId: 'marcaId',
  modeloId: 'modeloId',
  lotacaoId: 'lotacaoId',
  quantidadeCilindros: 'quantidadeCilindros',
  pesoCO2: 'pesoCO2',
  pesoN2: 'pesoN2',
  volumeCilindro: 'volumeCilindro',
  referenciaCilindro: 'referenciaCilindro',
  sistemaInsuflacao: 'sistemaInsuflacao',
  tiposValvulas: 'tiposValvulas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConteudoPackScalarFieldEnum = {
  id: 'id',
  tipoPackId: 'tipoPackId',
  racoesEmergencia: 'racoesEmergencia',
  aguaPotavel: 'aguaPotavel',
  kitPrimeirosSocorros: 'kitPrimeirosSocorros',
  comprimidosEnjooPorPessoa: 'comprimidosEnjooPorPessoa',
  sacosEnjooPorPessoa: 'sacosEnjooPorPessoa',
  foguetesParaquedas: 'foguetesParaquedas',
  fachosMao: 'fachosMao',
  sinaisFumo: 'sinaisFumo',
  lanternaEstanque: 'lanternaEstanque',
  heliógrafo: 'heliógrafo',
  apito: 'apito',
  faca: 'faca',
  esponjas: 'esponjas',
  abreLatas: 'abreLatas',
  coposGraduados: 'coposGraduados',
  mantasTermicas: 'mantasTermicas',
  kitPesca: 'kitPesca',
  manualSobrevivencia: 'manualSobrevivencia',
  tabelaSinais: 'tabelaSinais',
  foleEnchimento: 'foleEnchimento',
  tampoesFuros: 'tampoesFuros',
  kitReparacao: 'kitReparacao',
  ancorasQuantidade: 'ancorasQuantidade',
  luzInterna: 'luzInterna',
  luzExterna: 'luzExterna',
  bateria: 'bateria',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SistemaCilindroScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  descricao: 'descricao',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TipoCilindroScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  descricao: 'descricao',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TipoPackScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  descricao: 'descricao',
  categoria: 'categoria',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TipoValvulaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  descricao: 'descricao',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnvioScalarFieldEnum = {
  id: 'id',
  numeroRastreio: 'numeroRastreio',
  tipo: 'tipo',
  metodoEnvio: 'metodoEnvio',
  transportadora: 'transportadora',
  status: 'status',
  clienteId: 'clienteId',
  destinatarioNome: 'destinatarioNome',
  destinatarioEmail: 'destinatarioEmail',
  destinatarioTelefone: 'destinatarioTelefone',
  enderecoEntrega: 'enderecoEntrega',
  dataEnvio: 'dataEnvio',
  dataEntregaEstimada: 'dataEntregaEstimada',
  dataEntregaReal: 'dataEntregaReal',
  custoEnvio: 'custoEnvio',
  custoTotal: 'custoTotal',
  observacoes: 'observacoes',
  responsavel: 'responsavel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnvioItemScalarFieldEnum = {
  id: 'id',
  envioId: 'envioId',
  tipoItem: 'tipoItem',
  stockId: 'stockId',
  jangadaId: 'jangadaId',
  certificadoId: 'certificadoId',
  correspondenciaId: 'correspondenciaId',
  quantidade: 'quantidade',
  descricao: 'descricao'
};

exports.Prisma.CorrespondenciaScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  assunto: 'assunto',
  descricao: 'descricao',
  prioridade: 'prioridade',
  status: 'status',
  remetenteNome: 'remetenteNome',
  remetenteEmail: 'remetenteEmail',
  remetenteTelefone: 'remetenteTelefone',
  destinatarioNome: 'destinatarioNome',
  destinatarioEmail: 'destinatarioEmail',
  destinatarioTelefone: 'destinatarioTelefone',
  enderecoEntrega: 'enderecoEntrega',
  conteudo: 'conteudo',
  anexos: 'anexos',
  dataEnvio: 'dataEnvio',
  dataRecebimento: 'dataRecebimento',
  metodoEnvio: 'metodoEnvio',
  responsavel: 'responsavel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TarefaScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  descricao: 'descricao',
  tipo: 'tipo',
  status: 'status',
  prioridade: 'prioridade',
  dataVencimento: 'dataVencimento',
  dataConclusao: 'dataConclusao',
  contatoNome: 'contatoNome',
  contatoEmail: 'contatoEmail',
  contatoTelefone: 'contatoTelefone',
  stockId: 'stockId',
  clienteId: 'clienteId',
  quantidade: 'quantidade',
  criadoPor: 'criadoPor',
  responsavel: 'responsavel',
  notas: 'notas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Cliente: 'Cliente',
  Navio: 'Navio',
  Jangada: 'Jangada',
  Proprietario: 'Proprietario',
  Pessoa: 'Pessoa',
  Certificado: 'Certificado',
  Stock: 'Stock',
  MovimentacaoStock: 'MovimentacaoStock',
  Cilindro: 'Cilindro',
  Agendamento: 'Agendamento',
  Fatura: 'Fatura',
  Notificacao: 'Notificacao',
  Partner: 'Partner',
  Obra: 'Obra',
  PredictiveMaintenance: 'PredictiveMaintenance',
  Relatorio: 'Relatorio',
  Inspecao: 'Inspecao',
  CustoInspecao: 'CustoInspecao',
  HistoricoInspecao: 'HistoricoInspecao',
  InspecaoComponente: 'InspecaoComponente',
  SubstituicaoComponente: 'SubstituicaoComponente',
  MarcaJangada: 'MarcaJangada',
  ModeloJangada: 'ModeloJangada',
  ModeloJangadaItem: 'ModeloJangadaItem',
  LotacaoJangada: 'LotacaoJangada',
  EspecificacaoTecnica: 'EspecificacaoTecnica',
  ConteudoPack: 'ConteudoPack',
  SistemaCilindro: 'SistemaCilindro',
  TipoCilindro: 'TipoCilindro',
  TipoPack: 'TipoPack',
  TipoValvula: 'TipoValvula',
  Envio: 'Envio',
  EnvioItem: 'EnvioItem',
  Correspondencia: 'Correspondencia',
  Tarefa: 'Tarefa'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
