-- Alinhar tabela stock ao schema.prisma
ALTER TABLE "Stock"
  ADD COLUMN IF NOT EXISTS "categoria" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "associavelJangada" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "referencia" VARCHAR(255) UNIQUE,
  ADD COLUMN IF NOT EXISTS "descricao" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "aplicavelMarcaJangada" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "aplicavelModeloJangada" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "precoCompra" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "codigoFabricante" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "inventario" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "lote" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "validade" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "precoVenda" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "quantidade" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT NOW();
