export type LifejacketServiceItem = {
  name: string;
  reference?: string;
  notes?: string;
  interval?: string;
  mandatory?: boolean;
};

export type LifejacketModel = {
  model: string;
  manufacturingCountry?: string;
  family?: string;
  buoyancy: string;
  chamber: string;
  activation: string;
  certifications: string[];
  applications: string[];
  sizes: string[];
  characteristics: string[];
  serviceItems: LifejacketServiceItem[];
  manualFiles?: string[];
};

export type LifejacketBrandCatalog = {
  brand: string;
  manufacturingCountry?: string;
  summary: string;
  inflationSystems: string[];
  commonStandards: string[];
  models: LifejacketModel[];
};

export const lifejacketModelData: LifejacketBrandCatalog[] = [
  {
    brand: "EVAL",
    manufacturingCountry: "Grécia",
    summary: "Gama SIMI de coletes insufláveis 150N/170N ultraleves e compactos, com variantes manuais, automáticas, D-ring e versões com arnês/crotch strap.",
    inflationSystems: ["UML automatic", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["EN ISO 12402-3", "EN ISO 12402-7", "EN ISO 12402-8"],
    models: [
      {
        model: "SIMI",
        manufacturingCountry: "Grécia",
        family: "Recreio / Offshore leve",
        buoyancy: "150N (165N–170N real conforme variante)",
        chamber: "Câmara simples",
        activation: "Manual ou automático (UML)",
        certifications: ["EN ISO 12402-3", "EN ISO 12402-7", "EN ISO 12402-8"],
        applications: ["Águas não protegidas", "Embarcações de recreio", "Uso com roupa pesada"],
        sizes: ["Peso mínimo 40 kg", "Peito até 140 cm"],
        characteristics: [
          "Design ultraleve, compacto e ergonómico",
          "Vira o utilizador para posição de segurança face para cima",
          "Insuflador UML compatível com cilindro CO₂ de 33g",
          "Apito EN ISO 12402-8 e fita refletora SOLAS",
          "Inclui alça de resgate (lifting loop) e tubo oral com válvula de retenção",
          "Variantes com fivela plástica ou inox, com ou sem D-Ring",
          "Existe versão 170N com arnês e crotch strap",
        ],
        serviceItems: [
          { name: "Cilindro CO₂ 33g", notes: "Verificar massa, corrosão, rosca e aperto correto", interval: "Anual", mandatory: true },
          { name: "Mecanismo UML / indicador verde", notes: "Confirmar que o insuflador não disparou e que o indicador visual está verde", interval: "Anual", mandatory: true },
          { name: "Tubo oral e válvula de retenção", notes: "Insuflar oralmente e confirmar estanquicidade durante 12–24 horas", interval: "Anual", mandatory: true },
          { name: "Apito, fita refletora SOLAS e alça de resgate", notes: "Confirmar presença, integridade e fixação", interval: "Anual", mandatory: true },
          { name: "D-Ring / fivela / arnês / crotch strap", notes: "Aplicável conforme variante; verificar ferragens, costuras e desgaste", interval: "Anual" },
        ],
        manualFiles: ["UML Product Manual.pdf", "Lifejacket inflation Systems.docx"],
      },
    ],
  },
  {
    brand: "LALIZAS",
    manufacturingCountry: "Grécia",
    summary: "Família de coletes insufláveis LALIZAS com variantes por código de produto e sistemas manual, automático JS1 e hidrostático Hammar MA1.",
    inflationSystems: ["Lalizas manual operating head", "Lalizas JS1 automatic", "Hammar MA1 hydrostatic", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3", "ISO 12402-2", "SOLAS (modelos dedicados)"],
    models: [
      {
        model: "Sigma",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Recreio",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual (operating head) ou automático JS1",
        certifications: ["ISO 12402-3"],
        applications: ["Navegação costeira", "Embarcações de recreio", "Uso geral"],
        sizes: ["Adulto"],
        characteristics: [
          "Família Sigma Lalizas 150N",
          "Agrupa variantes Sigma manual e automática JS1",
          "Relacionado com as versões por código 71094, 71095, 71096 e 71097",
        ],
        serviceItems: [
          { name: "Lalizas manual operating head", notes: "Apertar porca com torque de 3 N.m no suporte do operating head", interval: "Anual", mandatory: true },
          { name: "Mecanismo automático JS1", notes: "Confirmar indicador verde e substituir water activated device em inspeção anual", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Substituir em cada inspeção anual recomendada pela Lalizas", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", notes: "Aplicável à família Sigma 150N", interval: "Anual", mandatory: true },
          { name: "Válvula oral e tubo oral", notes: "Inspeção funcional e estanquidade", interval: "Anual", mandatory: true },
          { name: "Fitas refletoras, apito, fivelas e cover", interval: "Anual" },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Sigma 150N",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Recreio",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual (operating head) ou automático JS1",
        certifications: ["ISO 12402-3"],
        applications: ["Navegação costeira", "Embarcações de recreio", "Uso geral"],
        sizes: ["Adulto"],
        characteristics: [
          "Versões por código: 71094, 71095, 71096, 71097",
          "Família com versões manual e automática JS1",
          "Indicador de pronto para ação (green ready tag / indicador verde)",
        ],
        serviceItems: [
          { name: "Lalizas manual operating head", notes: "Apertar porca com torque de 3 N.m no suporte do operating head", interval: "Anual", mandatory: true },
          { name: "Mecanismo automático JS1", notes: "Confirmar indicador verde e substituir water activated device em inspeção anual", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Substituir em cada inspeção anual recomendada pela Lalizas", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", notes: "Aplicável a versões adultas Sigma 150N", interval: "Anual", mandatory: true },
          { name: "Válvula oral e tubo oral", notes: "Inspeção funcional e estanquidade", interval: "Anual", mandatory: true },
          { name: "Fitas refletoras, apito, fivelas e cover", interval: "Anual" },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Alpha Auto 150N",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Adulto e Criança",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático JS1 + acionamento manual",
        certifications: ["ISO 12402-3"],
        applications: ["Recreio", "Uso geral", "Modelos adulto e criança"],
        sizes: ["Adulto", "Criança"],
        characteristics: [
          "Versões por código: 71098, 71099, 71100, 71101, 71102",
          "Inclui variantes para criança (71102)",
          "Sistema JS1 com componente ativado por água",
        ],
        serviceItems: [
          { name: "Mecanismo automático JS1", notes: "Inspecionar cap/indicador e estado do sistema", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Troca anual recomendada", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g (adulto)", notes: "Para versões adultas Alpha 150N", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 22g (criança)", notes: "Aplicável ao modelo infantil Alpha 150N", interval: "Anual", mandatory: true },
          { name: "Manual lever + green ready tag", notes: "Confirmar presença e posição correta", interval: "Anual", mandatory: true },
          { name: "Tubo oral, cover, costuras e fitas refletoras", interval: "Anual" },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Omega 150N",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Adulto",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual ou automático JS1 (conforme variante)",
        certifications: ["ISO 12402-3"],
        applications: ["Recreio", "Costeiro", "Uso geral"],
        sizes: ["Adulto"],
        characteristics: [
          "Versões por código: 71103, 71104, 71105, 71106",
          "Disponível em versões manual e automática",
        ],
        serviceItems: [
          { name: "Lalizas manual operating head", notes: "Aplicável às versões manuais", interval: "Anual", mandatory: true },
          { name: "Mecanismo automático JS1", notes: "Aplicável às versões automáticas", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Troca anual recomendada para versões automáticas", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Tubo oral, válvula e teste de estanquidade", interval: "Anual", mandatory: true },
          { name: "Cover, velcro/zip, fitas e apito", interval: "Anual" },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Delta Belt-Pack 150N",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Belt-Pack",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual ou automático JS1 (conforme variante)",
        certifications: ["ISO 12402-3", "SOLAS (variantes)"],
        applications: ["Recreio", "Utilização compacta belt-pack"],
        sizes: ["Adulto"],
        characteristics: [
          "Versões por código: 71108, 71109, 71201",
          "Inclui variantes manual e automática",
        ],
        serviceItems: [
          { name: "Mecanismo manual/automático conforme variante", notes: "Confirmar tipo instalado no código do produto", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Aplicável nas versões automáticas", interval: "Anual" },
          { name: "Cilindro CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Sistema belt-pack: costuras, fechos, webbing", interval: "Anual", mandatory: true },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Lamda Auto 150N SOLAS",
        manufacturingCountry: "Grécia",
        family: "SOLAS 150N",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático JS1 + acionamento manual",
        certifications: ["SOLAS"],
        applications: ["Comercial", "Profissional"],
        sizes: ["Adulto"],
        characteristics: [
          "Código de produto: 71107",
          "Sistema automático JS1 com indicador de pronto",
        ],
        serviceItems: [
          { name: "Mecanismo automático JS1", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Substituição anual recomendada", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Tubo oral, luz/apito (se equipados), fitas SOLAS", interval: "Anual" },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Lamda Auto 275N SOLAS",
        manufacturingCountry: "Grécia",
        family: "SOLAS 275N",
        buoyancy: "275N",
        chamber: "Câmara simples de alto volume",
        activation: "Automático JS1 + acionamento manual",
        certifications: ["SOLAS"],
        applications: ["Comercial", "Condições severas", "Roupa pesada"],
        sizes: ["Adulto"],
        characteristics: [
          "Código de produto: 71216",
          "Sistema automático JS1 com componente ativado por água",
        ],
        serviceItems: [
          { name: "Mecanismo automático JS1", interval: "Anual", mandatory: true },
          { name: "Water activated device", reference: "00340", notes: "Substituição anual recomendada", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 60g", notes: "Aplicável a Lamda 275N e Omega 275N", interval: "Anual", mandatory: true },
          { name: "Tubo oral, costuras estruturais e acessórios SOLAS", interval: "Anual", mandatory: true },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
      {
        model: "Epsilon 150N (Hammar MA1)",
        manufacturingCountry: "Grécia",
        family: "ISO 12402 / Hidrostático",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Hammar MA1 hidrostático + acionamento manual",
        certifications: ["ISO 12402-3"],
        applications: ["Recreio", "Offshore"],
        sizes: ["Adulto"],
        characteristics: [
          "Código associado no manual: 71725",
          "Secção dedicada ao rearmamento MA1 (manual sec. 5.3)",
        ],
        serviceItems: [
          { name: "Mecanismo hidrostático Hammar MA1", notes: "Inspeção e rearmamento conforme secção 5.3", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Bladder leakage test com solução água/sabão", notes: "Falha em material/costura implica reprovação do colete", interval: "Anual", mandatory: true },
          { name: "Registo de serviço (serial, data, pass/fail, inspetor)", interval: "Cada serviço", mandatory: true },
        ],
        manualFiles: ["LALIZAS - Service Manual for Inflatable Lifejackets.pdf"],
      },
    ],
  },
  {
    brand: "PLASTIMO",
    manufacturingCountry: "França",
    summary: "Gama recreio/offshore com famílias Pilot e kits de recarga específicos por modelo, mecanismo e gramagem de CO₂.",
    inflationSystems: ["UML Manual", "UML5 automático", "UML Pro Sensor Elite", "Hammar hidrostático (A1/MA1)", "manual pull cord"],
    commonStandards: ["ISO 12402-3", "ISO 12402-2"],
    models: [
      {
        model: "Pilot 165",
        manufacturingCountry: "França",
        family: "Cruzeiro / offshore leve",
        buoyancy: "165N",
        chamber: "Câmara simples",
        activation: "Manual ou automático (UML5 / Pro Sensor Elite / Hammar conforme variante)",
        certifications: ["ISO 12402-3"],
        applications: ["Cruzeiro", "Vela oceânica", "Tripulação de recreio"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Cobertura compacta com acesso rápido ao kit de serviço",
          "Versões com arnês e sem arnês",
          "Compatível com luz e sprayhood em variantes superiores",
          "Família 150N/165N com cilindro CO₂ de 33g",
          "Mecanismos suportados no guia de recarga: UML manual, UML5, Pro Sensor Elite e Hammar",
        ],
        serviceItems: [
          { name: "Kit recarga completo UML Manual 33g", reference: "40199", notes: "Aplicável em versões manuais sem cartucho automático", interval: "Anual", mandatory: true },
          { name: "Kit recarga completo UML5 Auto 33g", reference: "40200", notes: "Para versões automáticas UML5 de 150/165N", interval: "Anual", mandatory: true },
          { name: "Cartucho automático UML5", reference: "64114", notes: "Artigo de substituição do mecanismo UML5", interval: "Validade do cartucho", mandatory: true },
          { name: "Kit recarga completo Pro Sensor Elite 33g", reference: "58460", notes: "Alternativa automática para versões Pro Sensor", interval: "Anual", mandatory: true },
          { name: "Cartucho Pro Sensor Elite", reference: "64115", notes: "Substituir antes da validade indicada", interval: "Validade do cartucho", mandatory: true },
          { name: "Kit recarga completo Hammar 33g", reference: "40201", notes: "Sistema hidrostático A1/MA1 em variantes compatíveis", interval: "Anual", mandatory: true },
          { name: "Disparador hidrostático Hammar", reference: "42440", notes: "Substituição do elemento hidrostático", interval: "5 anos", mandatory: true },
          { name: "Cilindro CO₂ 33g", notes: "Conferir massa, corrosão e rosca", interval: "Anual", mandatory: true },
          { name: "Válvula oral e tampa", notes: "Ensaiar retenção de pressão da câmara", interval: "Anual", mandatory: true },
          { name: "Fechos, fita refletora, apito e luz (se instalada)", interval: "Anual" },
        ],
        manualFiles: ["MANUAL PLASTIMO COLETES.PDF"],
      },
      {
        model: "Pilot 290",
        manufacturingCountry: "França",
        family: "Offshore pesado",
        buoyancy: "290N",
        chamber: "Câmara simples de alto volume",
        activation: "Automático (UML5 / Pro Sensor Elite / Hammar conforme versão) ou manual",
        certifications: ["ISO 12402-2"],
        applications: ["Roupa pesada de proteção", "Offshore profissional", "Condições frias"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Maior volume de bladder para roupa de trabalho",
          "Maior força de rotação e sustentação",
          "Versões com arnês integrado",
          "Modelo heavy-duty com cilindro CO₂ de 60g",
          "Guia Plastimo identifica kits específicos Pilot 290 para mecanismos automáticos",
        ],
        serviceItems: [
          { name: "Kit recarga completo UML Manual 60g", reference: "50374", notes: "Aplicável a versões manuais de alta capacidade", interval: "Anual", mandatory: true },
          { name: "Kit recarga completo UML5 Auto 60g", reference: "50375", notes: "Para versões automáticas Pilot 275/290", interval: "Anual", mandatory: true },
          { name: "Cartucho automático UML5", reference: "40255", notes: "Artigo de reposição do mecanismo UML5", interval: "Validade do cartucho", mandatory: true },
          { name: "Kit recarga completo Pro Sensor Elite 60g", reference: "61654", notes: "Versões automáticas com Pro Sensor Elite", interval: "Anual", mandatory: true },
          { name: "Cartucho Pro Sensor Elite", reference: "58505", notes: "Substituição por validade/indicador", interval: "Validade do cartucho", mandatory: true },
          { name: "Kit recarga completo Hammar 60g", reference: "50376", notes: "Versões hidrostáticas 275/290", interval: "Anual", mandatory: true },
          { name: "Disparador hidrostático Hammar", reference: "61671 / 65639 (Pilot 290)", notes: "Elemento hidrostático com ciclo de troca periódico", interval: "5 anos", mandatory: true },
          { name: "Cilindro CO₂ 60g", notes: "Confirmar gramagem, corrosão e estanquidade", interval: "Anual", mandatory: true },
          { name: "Luz, sprayhood e crutch strap", notes: "Verificar presença e estado quando equipados", interval: "Anual" },
        ],
        manualFiles: ["MANUAL PLASTIMO COLETES.PDF"],
      },
    ],
  },
  {
    brand: "CREWSAVER",
    manufacturingCountry: "Reino Unido",
    summary: "Biblioteca técnica rica com famílias Crewfit, Seacrewsader, Voyager, Seafire e modelos SOLAS/twin chamber.",
    inflationSystems: ["UML automatic", "Hammar em alguns conjuntos", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3", "ISO 12402-2", "SOLAS", "MED"],
    models: [
      {
        model: "Crewfit 150N",
        manufacturingCountry: "Reino Unido",
        family: "Crewfit recreio",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Recreio", "Costeiro", "Tripulação ligeira"],
        sizes: ["Adulto universal"],
        characteristics: ["Família base Crewfit", "Versões junior e adulto", "Cobertura compacta com acesso rápido ao sistema de disparo"],
        serviceItems: [
          { name: "CO₂ cylinder", interval: "Anual", mandatory: true },
          { name: "Automatic firing mechanism", interval: "Anual", mandatory: true },
          { name: "Manual pull toggle and indicator", interval: "Anual", mandatory: true },
          { name: "Bladder leak test + oral tube test", interval: "Anual", mandatory: true },
        ],
        manualFiles: ["crewfit-150-servicing-manual-issue-15.pdf", "crewfit-150n-junior-manual-issue-1.pdf", "cwx-150n-servicing-manual-issue-3.pdf"],
      },
      {
        model: "Crewfit 165 Classic",
        manufacturingCountry: "Reino Unido",
        family: "Crewfit offshore",
        buoyancy: "165N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Cruzeiro", "Vela offshore", "Trabalho leve"],
        sizes: ["Adulto universal"],
        characteristics: ["Formato clássico com maior suporte cervical", "Variantes com arnês e luz"],
        serviceItems: [
          { name: "CO₂ cylinder", interval: "Anual", mandatory: true },
          { name: "Inflator head + bobbin", interval: "Anual", mandatory: true },
          { name: "Light / sprayhood / crotch strap", interval: "Anual" },
        ],
        manualFiles: ["crewfit-165-classic-manual-issue-2.pdf"],
      },
      {
        model: "Crewfit 180 Pro / 190",
        manufacturingCountry: "Reino Unido",
        family: "Crewfit profissional",
        buoyancy: "180N–190N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Profissional", "Pilotagem", "Uso intensivo"],
        sizes: ["Adulto universal"],
        characteristics: ["Construção reforçada", "Acessórios de serviço frequente", "Configurações com arnês"],
        serviceItems: [
          { name: "Cylinder + firing head", interval: "Anual", mandatory: true },
          { name: "Harness webbing and D-ring inspection", interval: "Anual", mandatory: true },
          { name: "Cover, zip, buckle and oral tube check", interval: "Anual", mandatory: true },
        ],
        manualFiles: ["crewfit-180-pro-manual-issue-2.pdf", "crewfit_190_servicing_manual_issue_5.pdf", "snsm-ergofit-190n-twin-chamber-manual-issue-1.pdf"],
      },
      {
        model: "Crewfit 275 / 290 / XD275",
        manufacturingCountry: "Reino Unido",
        family: "Heavy duty / offshore pesado",
        buoyancy: "275N–290N",
        chamber: "Câmara simples de alto volume",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-2"],
        applications: ["Roupa pesada", "Profissional offshore", "Condições extremas"],
        sizes: ["Adulto universal"],
        characteristics: ["Elevada força de rotação", "Compatível com vestuário de trabalho e EPIs", "Variantes XD reforçadas"],
        serviceItems: [
          { name: "High-volume CO₂ cylinder", interval: "Anual", mandatory: true },
          { name: "Auto-manual rearming kit", interval: "Anual", mandatory: true },
          { name: "Sprayhood, light and buddy line", interval: "Anual" },
        ],
        manualFiles: ["crewfit-275-servicing-manual-issue-14.pdf", "crewfit-290-servicing-manual-issue-3.pdf", "crewfit-xd150n-and-xd275n-servicing-manual-issue-1_oct-2019.pdf", "offshore-290-servicing-manual-issue-2.pdf"],
      },
      {
        model: "Crewfit Twin / Twin Chamber",
        manufacturingCountry: "Reino Unido",
        family: "Redundante",
        buoyancy: "Twin chamber",
        chamber: "Dupla câmara",
        activation: "Duplo automático/manual",
        certifications: ["SOLAS / profissional conforme variante"],
        applications: ["Profissional", "Resgate", "Redundância operacional"],
        sizes: ["Adulto universal"],
        characteristics: ["Duas câmaras independentes", "Redundância de insuflação", "Maior segurança em operações críticas"],
        serviceItems: [
          { name: "Dual cylinders", interval: "Anual", mandatory: true },
          { name: "Dual firing heads", interval: "Anual", mandatory: true },
          { name: "Dual chamber leak test", interval: "Anual", mandatory: true },
        ],
        manualFiles: ["crewfit-twin-servicing-manual-issue-12.pdf", "crewfit_twin_servicing_manual_issue_10.pdf"],
      },
      {
        model: "Seacrewsader / Voyager / Seafire SOLAS",
        manufacturingCountry: "Reino Unido",
        family: "Solas e especialidades",
        buoyancy: "150N–275N / SOLAS",
        chamber: "Simples ou dupla conforme série",
        activation: "Automático/manual conforme série",
        certifications: ["SOLAS", "MED", "ISO 12402"],
        applications: ["Comercial", "Muster / abandono", "Passageiros e tripulação"],
        sizes: ["Adulto", "Séries especiais"],
        characteristics: ["Modelos dedicados a conformidade SOLAS", "Alguns com packing manual separado", "Famílias Voyager e SeaFire orientadas a serviço regular"],
        serviceItems: [
          { name: "CO₂ cylinder(s)", interval: "Anual", mandatory: true },
          { name: "Inflator(s) + indicators", interval: "Anual", mandatory: true },
          { name: "Light, whistle, retro-reflective tape, buddy line", interval: "Anual", mandatory: true },
          { name: "Packing inspection and re-stow procedure", interval: "Anual", mandatory: true },
        ],
        manualFiles: [
          "150n-seacrewsader-2010-manual-issue-3.pdf",
          "crewsaver-275n-seacrewsader-2010-manual.pdf",
          "seacrewsader-servicing-manual-issue-8.pdf",
          "voyager-150-servicing-manual-issue-4.pdf",
          "voyager-275-servicing-manual-issue-2.pdf",
          "seafire_solas_servicing_manual_issue_11.pdf"
        ],
      },
    ],
  },
  {
    brand: "MULLION",
    manufacturingCountry: "Reino Unido",
    summary: "Modelo profissional Hi-Rise 275N SOLAS com dupla câmara e mecanismo hidrostático Hammar, conforme manual de serviço onboard.",
    inflationSystems: ["Hammar hydrostatic automatic", "manual pull cord", "oral inflation tube"],
    commonStandards: ["SOLAS", "MED"],
    models: [
      {
        model: "Hi-Rise 275N",
        manufacturingCountry: "Reino Unido",
        family: "Profissional / SOLAS",
        buoyancy: "275N",
        chamber: "Dupla câmara",
        activation: "Automático hidrostático (Hammar) com acionamento manual",
        certifications: ["SOLAS", "MED"],
        applications: ["Navios comerciais", "Operações offshore", "Condições severas com roupa de proteção"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Lifejacket twin chamber com redundância de insuflação",
          "Mecanismo automático hidrostático Hammar",
          "Harness/waist belt 50 mm com D-ring no cinto frontal",
          "Crutch strap frontal e traseiro com retenção",
          "Luz de emergência automática SOLAS e apito",
          "Buddy line com toggle e fitas refletoras SOLAS",
        ],
        serviceItems: [
          { name: "Materiais gerais/webbing/fivelas/crutch strap", notes: "Inspecionar danos, rasgos e integridade de todos os componentes", interval: "12 meses", mandatory: true },
          { name: "Costuras gerais", notes: "Verificar se todas as costuras estão intactas e seguras", interval: "12 meses", mandatory: true },
          { name: "Fechos zip e velcro", notes: "Confirmar fecho completo, integridade e retenção", interval: "12 meses", mandatory: true },
          { name: "Fitas refletoras SOLAS", notes: "Confirmar adesão e integridade nas câmaras insufláveis", interval: "12 meses", mandatory: true },
          { name: "Luz automática de emergência", notes: "Testar manualmente e/ou por imersão; confirmar fixação", interval: "12 meses", mandatory: true },
          { name: "Apito", notes: "Confirmar presença, fixação e funcionalidade", interval: "12 meses", mandatory: true },
          { name: "Mecanismo Hammar", notes: "Validar prazo, janela verde, pega manual e ausência de danos", interval: "12 meses", mandatory: true },
          { name: "Cilindro(s) CO₂", notes: "Sem perfuração/corrosão e idade inferior a 10 anos", interval: "12 meses", mandatory: true },
          { name: "Tubos/válvulas orais + teste de estanquidade", notes: "Insuflar ambas as câmaras e manter 12 horas; rejeitar se houver perda de pressão", interval: "12 meses", mandatory: true },
          { name: "Buddy line", notes: "Verificar corde/toggle íntegros e presentes", interval: "12 meses", mandatory: true },
          { name: "Rearm kit Hammar correto + torque de cilindro", notes: "Rearmar com kit correto e torque máximo de 10 Nm", interval: "Após disparo/imersão", mandatory: true },
        ],
        manualFiles: ["Mullion Hi-Rise 275N.pdf"],
      },
    ],
  },
  {
    brand: "SPINLOCK",
    manufacturingCountry: "Reino Unido",
    summary: "Deckvest DURO FC com variantes 170N e 275N, firing head UML (Mk5i ou Pro Sensor Elite) e componentes de serviço dedicados.",
    inflationSystems: ["UML Mk5i automatic", "UML Pro Sensor Elite automatic", "manual pull cord", "oral inflation tube"],
    commonStandards: ["ISO 12402-3:2020", "ISO 12402-2:2020"],
    models: [
      {
        model: "Deckvest DURO FC 170N",
        manufacturingCountry: "Reino Unido",
        family: "Profissional / Offshore",
        buoyancy: "170N",
        chamber: "Câmara simples",
        activation: "Automático UML Mk5i/Pro Sensor Elite com acionamento manual",
        certifications: ["ISO 12402-3:2020"],
        applications: ["Operação offshore", "Tripulação profissional", "Ambiente com EPI"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Quick Burst Zip frontal com indicador",
          "Crotch strap 40 mm extra-wide",
          "Heavy-duty buckle e sistema de ajuste de ombro",
          "Compatível com AIS MOB1, luz Pylon e Lume-On",
          "Sprayhood integrada",
        ],
        serviceItems: [
          { name: "Harness/cover/webbing/buckles/costuras", notes: "Inspeção de desgaste, danos, contaminação e passagem correta das fitas", interval: "Anual", mandatory: true },
          { name: "Quick Burst Zip", notes: "Verificar dentes, cursor e secção amarela de abertura rápida", interval: "Anual", mandatory: true },
          { name: "Teste de insuflação da câmara", notes: "Insuflar ~2 psi (14 kPa), deixar 24h em temperatura estável; se perda > ~10% substituir bladder", interval: "Anual", mandatory: true },
          { name: "Firing head UML Mk5i/Pro Sensor", notes: "Verificar estado, cartucho automático com validade mínima de 2 anos e indicadores ativos", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 33g", notes: "Conferir massa/especificação, corrosão e vedação (O-ring/gasket)", interval: "Anual", mandatory: true },
          { name: "Tubo oral, tampa, sprayhood, apito e luz", notes: "Confirmar presença, fixação e funcionamento (incl. teste da Pylon Light)", interval: "Anual", mandatory: true },
          { name: "MOB1 AIS (quando instalado)", notes: "Validar ribbon/clip/toggle e lanyard de segurança", interval: "Anual" },
          { name: "Idade do colete", notes: "Unidades com mais de 10 anos não devem ser intervencionadas", interval: "Contínuo", mandatory: true },
        ],
        manualFiles: ["spinlok deckvest duro fc.pdf"],
      },
      {
        model: "Deckvest DURO FC 275N",
        manufacturingCountry: "Reino Unido",
        family: "Profissional / Heavy Duty",
        buoyancy: "275N",
        chamber: "Câmara simples de alto volume",
        activation: "Automático UML Mk5i/Pro Sensor Elite com acionamento manual",
        certifications: ["ISO 12402-2:2020"],
        applications: ["Condições severas", "Uso com vestuário pesado", "Offshore profissional"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Arquitetura Deckvest DURO FC reforçada",
          "Compatível com Pro-TECH protective cover",
          "Sistema frontal de abertura rápida para serviço",
          "Elevada sustentação para roupa de proteção",
        ],
        serviceItems: [
          { name: "Harness/cover/webbing/buckles/costuras", notes: "Inspeção de desgaste, danos, contaminação e passagem correta das fitas", interval: "Anual", mandatory: true },
          { name: "Quick Burst Zip", notes: "Verificar dentes, cursor e secção amarela de abertura rápida", interval: "Anual", mandatory: true },
          { name: "Teste de insuflação da câmara", notes: "Insuflar ~2 psi (14 kPa), deixar 24h em temperatura estável; se perda > ~10% substituir bladder", interval: "Anual", mandatory: true },
          { name: "Firing head UML Mk5i/Pro Sensor", notes: "Verificar estado, cartucho automático com validade mínima de 2 anos e indicadores ativos", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ 60g", notes: "Conferir massa/especificação, corrosão e vedação (O-ring/gasket)", interval: "Anual", mandatory: true },
          { name: "Tubo oral, tampa, sprayhood, apito e luz", notes: "Confirmar presença, fixação e funcionamento (incl. teste da Pylon Light)", interval: "Anual", mandatory: true },
          { name: "MOB1 AIS (quando instalado)", notes: "Validar ribbon/clip/toggle e lanyard de segurança", interval: "Anual" },
          { name: "Idade do colete", notes: "Unidades com mais de 10 anos não devem ser intervencionadas", interval: "Contínuo", mandatory: true },
        ],
        manualFiles: ["spinlok deckvest duro fc.pdf"],
      },
    ],
  },
  {
    brand: "ISP",
    manufacturingCountry: "Reino Unido",
    summary: "Gama ISP Challenger desenhada e fabricada no Reino Unido para uso comercial, SOLAS, offshore e serviços de emergência, com bladders interlocking / Wave Barrier e mecanismos Halkey Roberts, UML e Hammar conforme a variante.",
    inflationSystems: ["Halkey Roberts Alpha automatic", "UML Pro Sensor Elite automatic", "United Moulders automatic / MK5", "Hammar hydrostatic", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["ISO 12402", "SOLAS", "CE (configurações aplicáveis)", "USCG (algumas configurações)"],
    models: [
      {
        model: "Challenger",
        manufacturingCountry: "Reino Unido",
        family: "Plataforma Challenger / referência genérica",
        buoyancy: "115N a 331N real, conforme modelo",
        chamber: "Câmara simples",
        activation: "Manual, automático ou hidrostático conforme versão",
        certifications: ["ISO 12402", "SOLAS"],
        applications: ["Comercial marinho", "Offshore", "Serviços de emergência", "Abandono / constant wear"],
        sizes: ["Adulto", "Júnior / criança em variantes dedicadas"],
        characteristics: [
          "Desenvolvido, projetado e fabricado no Reino Unido pela International Safety Products",
          "Plataforma com bladder interlocking e Wave Barrier Technology nas linhas 150N/170N/275N",
          "Compatível com mecanismos Halkey Roberts, UML e Hammar conforme o produto",
          "Variações com harness, deck belt, fire-retardant cover, AIS, sprayhood, luz e extended service em foil bag",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", notes: "Confirmar gramagem correta do modelo (33g / 60g ou equivalente), massa, corrosão e aperto", interval: "Anual", mandatory: true },
          { name: "Operating head / firing head", notes: "Verificar tipo instalado (Halkey Roberts / UML / Hammar), indicador, clip e retenção", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", notes: "Insuflar e confirmar retenção de pressão conforme procedimento do fabricante", interval: "Anual", mandatory: true },
          { name: "Webbing, buckle, harness, crotch strap e cover", notes: "Inspecionar desgaste, cortes, fivelas e fechos rápidos / zip / hook-and-loop", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Worksafe 170",
        manufacturingCountry: "Reino Unido",
        family: "Commercial marine workwear",
        buoyancy: "170N real / 150N categoria",
        chamber: "Câmara simples interlocking",
        activation: "Automático Halkey Roberts Alpha; opções manual, United Moulders ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Trabalho manual pesado", "Uso comercial", "Ambiente industrial / marítimo"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Wave Barrier Technology e self-righting em menos de 5 segundos",
          "Fecho frontal em inox e versão deck harness disponível",
          "Capas Orange PVC, heavy-duty PVC, fire retardant e red nylon",
          "AIS compatible, sprayhood, luz e crotch strap como opções",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar indicador e retenção do sistema; confirmar compatibilidade da cabeça HR instalada", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 33g", notes: "Aplicável à categoria 150N / 170N", interval: "Anual", mandatory: true },
          { name: "Bladder interlocking + teste de estanquidade", notes: "Confirmar forma do bladder, retenção e ausência de fugas", interval: "Anual", mandatory: true },
          { name: "Harness / buckle / cover / reflective binding", notes: "Inspecionar ferragens, cover quick-burst e fitas refletoras", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Worksafe 300",
        manufacturingCountry: "Reino Unido",
        family: "Commercial marine workwear heavy-duty",
        buoyancy: "300N real / 275N categoria",
        chamber: "Câmara simples",
        activation: "Automático Halkey Roberts Alpha; opções manual, United Moulders ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Roupa pesada", "Uso comercial offshore", "Condições exigentes"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Mesma arquitetura Worksafe com maior sustentação para vestuário pesado",
          "Versões standard e deck harness",
          "Capas industriais incluindo PVC laranja, nylon vermelho e variantes fire retardant",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar indicador, clip e estado geral do operating head", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 60g", notes: "Aplicável à categoria 275N / 300N", interval: "Anual", mandatory: true },
          { name: "Bladder + wave barrier / freeboard", notes: "Inspecionar retenção de pressão e formato do bladder para roupa pesada", interval: "Anual", mandatory: true },
          { name: "Harness / buckle / cover industrial", notes: "Verificar costuras, ferragens e integridade do cover", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Worksafe Pro 170",
        manufacturingCountry: "Reino Unido",
        family: "Commercial marine workwear Pro",
        buoyancy: "170N real / 150N categoria",
        chamber: "Câmara simples",
        activation: "Automático UML Pro Sensor Elite; opções manual, Halkey Roberts ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Uso comercial intensivo", "Tripulações profissionais", "AIS-ready workwear"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Design ergonómico slim fit com mesh back e proteção em neoprene no pescoço",
          "Janela de inspeção do firing head e ponto de fixação para rádio",
          "Wave Barrier Technology e self-righting < 5 segundos",
          "Versão com harness disponível",
        ],
        serviceItems: [
          { name: "UML Pro Sensor Elite Automatic", notes: "Verificar janela do firing head, indicador e estado do cartucho automático", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 33g", notes: "Gramagem típica da versão 170N", interval: "Anual", mandatory: true },
          { name: "Zip closure / protective tab / crotch strap", notes: "Inspecionar fecho, tab de proteção e strap integral", interval: "Anual", mandatory: true },
          { name: "AIS-ready fittings / radio attachment / harness", notes: "Confirmar pontos de fixação e ferragens quando equipados", interval: "Anual" },
        ],
      },
      {
        model: "Challenger Worksafe Pro 300",
        manufacturingCountry: "Reino Unido",
        family: "Commercial marine workwear Pro heavy-duty",
        buoyancy: "300N real / 275N categoria",
        chamber: "Câmara simples",
        activation: "Automático UML Pro Sensor Elite; opções manual, Halkey Roberts ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Roupa pesada", "Offshore profissional", "Ambiente abrasivo"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Estrutura Worksafe Pro com suporte respirável e maior flutuabilidade",
          "Janela de firing head e cobertura reforçada para uso intensivo",
          "Versões standard e deck harness",
        ],
        serviceItems: [
          { name: "UML Pro Sensor Elite Automatic", notes: "Verificar firing head, janela e estado do cartucho automático", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 60g", notes: "Aplicável à plataforma 300N / 275N", interval: "Anual", mandatory: true },
          { name: "Zip closure / mesh back / neoprene neck", notes: "Inspecionar desgaste e abrasão do conjunto Pro", interval: "Anual", mandatory: true },
          { name: "Harness / AIS / sprayhood / luz", notes: "Confirmar acessórios instalados na configuração do utilizador", interval: "Anual" },
        ],
      },
      {
        model: "Challenger SOLAS Flexi-Wing 150",
        manufacturingCountry: "Reino Unido",
        family: "SOLAS constant wear / abandonment",
        buoyancy: "173N real / 150N categoria",
        chamber: "Dupla câmara independente",
        activation: "Automático Halkey Roberts Alpha; opções United Moulders ou Hammar",
        certifications: ["SOLAS"],
        applications: ["Abandono", "Constant wear", "Compatível com abandonment suit"],
        sizes: ["Adulto"],
        characteristics: [
          "Design Flexi-Wing de perfil baixo com maior mouth freeboard",
          "Interlocking lobe + wave barrier com rotação em menos de 5 segundos",
          "Luz SOLAS, buddy line, lifting becket e retro-reflective tape",
          "Deck harness e sprayhood como opções",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar operating head automático e acessibilidade do sistema", interval: "Anual", mandatory: true },
          { name: "Cilindro(s) CO₂ de plataforma 150N SOLAS", notes: "Conferir gramagem/especificação instalada conforme twin chamber", interval: "Anual", mandatory: true },
          { name: "Twin chambers + localização light + buddy line", notes: "Testar ambas as câmaras e acessórios SOLAS", interval: "Anual", mandatory: true },
          { name: "Cover high-visibility / sprayhood / harness", notes: "Inspecionar cover, retro tape e deck harness quando equipado", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Interlock 275",
        manufacturingCountry: "Reino Unido",
        family: "SOLAS combined working / abandonment",
        buoyancy: "330N real / 275N categoria",
        chamber: "Dupla câmara",
        activation: "Automático Halkey Roberts Alpha; opções United Moulders ou Hammar",
        certifications: ["SOLAS"],
        applications: ["Roupa pesada", "Abandono", "Trabalho / abandono combinado"],
        sizes: ["Adulto"],
        characteristics: [
          "Twin chamber bladder com interlocking lobes e Wave Barrier Technology",
          "Luz, buddy line, retro tape e lifting becket integrados",
          "Suporta AIS Recovery System e cover em nylon, PVC ou Panotex fire-resistant",
          "Disponível com harness, sprayhood, extender belt e crotch strap",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar cabeça automática HR e indicador", interval: "Anual", mandatory: true },
          { name: "Cilindro(s) CO₂ de plataforma 275N", notes: "Confirmar especificação twin chamber / high buoyancy instalada", interval: "Anual", mandatory: true },
          { name: "Twin chambers + wave barrier", notes: "Testar as duas câmaras e forma do bladder interlock", interval: "Anual", mandatory: true },
          { name: "SOLAS light / buddy line / harness / cover", notes: "Inspecionar acessórios e cover conforme configuração", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger SOLAS Aqua Junior 100",
        manufacturingCountry: "Reino Unido",
        family: "SOLAS júnior / criança",
        buoyancy: "115N real / 100N categoria",
        chamber: "Dupla câmara",
        activation: "Automático Halkey Roberts Alpha",
        certifications: ["SOLAS"],
        applications: ["Crianças 15 kg a 43 kg", "Abandono SOLAS", "Segurança infantil a bordo"],
        sizes: ["15 kg a 43 kg"],
        characteristics: [
          "Versão infantil da linha SOLAS ISP",
          "Deck belt e crotch straps montados de origem",
          "Lifejacket light, buddy line, whistle e twin chamber para segurança acrescida",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar cabeça automática e retenção do sistema", interval: "Anual", mandatory: true },
          { name: "Twin chambers + ajuste infantil", notes: "Testar as duas câmaras e o ajuste de deck belt / crotch strap", interval: "Anual", mandatory: true },
          { name: "Luz, buddy line e lifting becket", notes: "Confirmar presença e funcionalidade dos acessórios SOLAS", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Worksafe Pro Ambulance",
        manufacturingCountry: "Reino Unido",
        family: "Emergency services",
        buoyancy: "331N real / 275N categoria",
        chamber: "Câmara simples",
        activation: "Automático Halkey Roberts Alpha; opções manual, UML ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Ambulância", "Serviços de emergência", "Resgate profissional"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Base Worksafe Pro 300 adaptada a serviços de emergência",
          "Padrão retro-refletor de emergência e lettering 'AMBULANCE'",
          "Radio clip x2, quick burst zip closure e 60g gas cylinder",
          "Wave Barrier Technology e elevada freeboard",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar firing head automático e opções instaladas", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 60g", notes: "Aplicável à versão de 331N / categoria 275N", interval: "Anual", mandatory: true },
          { name: "Radio clips / reflective check pattern / lettering", notes: "Inspecionar acessórios específicos da versão Ambulance", interval: "Anual", mandatory: true },
          { name: "Quick burst zip / crotch strap / carry bag", notes: "Verificar fecho, strap fixo e estado do saco de transporte", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Challenger Worksafe Pro Fire",
        manufacturingCountry: "Reino Unido",
        family: "Emergency services",
        buoyancy: "331N real / 275N categoria",
        chamber: "Câmara simples",
        activation: "Automático Halkey Roberts Alpha; opções manual, UML ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Bombeiros", "Serviços de emergência", "Resgate profissional"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Especificação derivada do Worksafe Pro de emergência com colorway Fire",
          "Padrão retro-refletor de emergência, quick burst zip e 60g gas cylinder",
          "Radio clip x2 e opções de sprayhood, AIS/PLB e luz AQ40",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar cabeça automática e opções de firing head alternativas", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 60g", interval: "Anual", mandatory: true },
          { name: "Fire cover / reflective markings / radio clips", notes: "Inspecionar cover, marcações e fixações específicas", interval: "Anual", mandatory: true },
          { name: "Quick burst zip / crotch strap / AQ40 light", notes: "Verificar acessórios opcionais / instalados", interval: "Anual" },
        ],
      },
      {
        model: "Challenger Worksafe Pro Police",
        manufacturingCountry: "Reino Unido",
        family: "Emergency services",
        buoyancy: "331N real / 275N categoria",
        chamber: "Câmara simples",
        activation: "Automático Halkey Roberts Alpha; opções manual, UML ou Hammar",
        certifications: ["ISO 12402"],
        applications: ["Polícia marítima / fluvial", "Serviços de emergência", "Resgate profissional"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Especificação de serviços de emergência com colorway Police",
          "Padrão retro-refletor, quick burst zip e 60g gas cylinder",
          "Integração possível de AIS/PLB, AQ40 light e radio dock",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar operating head e estado do indicador", interval: "Anual", mandatory: true },
          { name: "Cilindro CO₂ de 60g", interval: "Anual", mandatory: true },
          { name: "Police cover / reflective markings / radio clips", notes: "Inspecionar acabamento e acessórios específicos da versão Police", interval: "Anual", mandatory: true },
          { name: "Quick burst zip / crotch strap / AIS", notes: "Confirmar fecho e acessórios opcionais / instalados", interval: "Anual" },
        ],
      },
      {
        model: "Challenger Interlock 275 Series III Offshore",
        manufacturingCountry: "Reino Unido",
        family: "SOLAS offshore / oil & gas",
        buoyancy: "300N real / 275N categoria",
        chamber: "Dupla câmara",
        activation: "Automático Halkey Roberts Alpha",
        certifications: ["SOLAS"],
        applications: ["Oil & Gas", "Offshore profissional", "Extended service em foil bag"],
        sizes: ["Adulto"],
        characteristics: [
          "Versão non-harness orientada ao mercado offshore / abrasivo",
          "PVC laranja flexível, sprayhood e lifejacket light montados",
          "Fornecido em foil bag para programa de serviço alargado",
          "Wave Barrier Technology e twin chamber 300N",
        ],
        serviceItems: [
          { name: "Halkey Roberts Alpha Automatic", notes: "Verificar cabeça automática e acessibilidade do sistema", interval: "Anual", mandatory: true },
          { name: "Twin chamber bladder + foil bag condition", notes: "Testar câmaras e inspecionar integridade da embalagem de serviço alargado", interval: "Anual", mandatory: true },
          { name: "Sprayhood / light / crotch strap / buddy line", notes: "Confirmar acessórios montados e em bom estado", interval: "Anual", mandatory: true },
          { name: "Plastic buckle / adjustable fit / abandonment-suit compatibility", notes: "Verificar fivela e conjunto de ajuste", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "HERO",
    summary: "Marca HERO adicionada ao catálogo para seleção imediata no formulário e filtros de coletes.",
    inflationSystems: ["manual pull cord", "automatic inflator", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3"],
    models: [
      {
        model: "HERO 150N",
        family: "Recreio / uso geral",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual ou automático",
        certifications: ["ISO 12402-3"],
        applications: ["Embarcações de recreio", "Uso geral"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Entrada base para permitir seleção da marca HERO no módulo",
          "Compatível com manutenção anual padrão de coletes insufláveis",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "Orange Marine",
    manufacturingCountry: "França",
    summary: "Marca Orange Marine adicionada ao catálogo para disponibilizar a seleção direta no formulário e nos filtros de coletes.",
    inflationSystems: ["manual pull cord", "automatic inflator", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3"],
    models: [
      {
        model: "Orange Marine 150N",
        manufacturingCountry: "França",
        family: "Recreio / uso geral",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual ou automático",
        certifications: ["ISO 12402-3"],
        applications: ["Embarcações de recreio", "Uso geral", "Costeiro"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Entrada técnica base para permitir seleção imediata da marca Orange Marine no módulo de coletes",
          "Compatível com manutenção anual padrão de coletes insufláveis",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Essential",
        manufacturingCountry: "França",
        family: "Recreio / uso geral",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual ou automático",
        certifications: ["ISO 12402-3"],
        applications: ["Embarcações de recreio", "Uso geral", "Costeiro"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo Essential associado à marca Orange Marine para seleção direta no formulário",
          "Configuração base compatível com manutenção anual padrão de coletes insufláveis",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "USHIP",
    manufacturingCountry: "França",
    summary: "Gama USHIP 165N com variantes UML e HAMMAR, com e sem arnês, identificadas no catálogo oficial USHIP.",
    inflationSystems: ["UML", "HAMMAR MA1", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3"],
    models: [
      {
        model: "USHIP 165N UML SEM ARNÊS",
        manufacturingCountry: "França",
        family: "Recreio / Costeiro",
        buoyancy: "165N",
        chamber: "Câmara simples",
        activation: "Automático UML + manual",
        certifications: ["ISO 12402-3"],
        applications: ["Vela", "Pesca", "Regata", "Lazer náutico"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Sem arnês",
          "Cartucho CO₂ 33g",
          "Percutor UML",
          "Inclui sangle sous-cutale (fita entrepernas)",
        ],
        serviceItems: [
          { name: "Cartucho CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Kit percutor UML + clip", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "USHIP 165N UML COM ARNÊS",
        manufacturingCountry: "França",
        family: "Offshore leve",
        buoyancy: "165N",
        chamber: "Câmara simples",
        activation: "Automático UML + manual",
        certifications: ["ISO 12402-3"],
        applications: ["Vela", "Pesca", "Regata", "Lazer náutico"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Com arnês",
          "Cartucho CO₂ 33g",
          "Percutor UML",
          "Inclui sangle sous-cutale (fita entrepernas)",
        ],
        serviceItems: [
          { name: "Cartucho CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Kit percutor UML + clip", interval: "Anual", mandatory: true },
          { name: "Inspeção de arnês/fivelas", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "USHIP 165N HAMMAR COM ARNÊS",
        manufacturingCountry: "França",
        family: "Offshore",
        buoyancy: "165N",
        chamber: "Câmara simples",
        activation: "Automático HAMMAR MA1 + manual",
        certifications: ["ISO 12402-3"],
        applications: ["Vela", "Pesca", "Regata", "Lazer náutico"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Com arnês",
          "Cartucho CO₂ 33g",
          "Percutor hidrostático HAMMAR MA1",
          "Inclui sangle sous-cutale (fita entrepernas)",
        ],
        serviceItems: [
          { name: "Cartucho CO₂ 33g", interval: "Anual", mandatory: true },
          { name: "Kit HAMMAR MA1", interval: "Anual", mandatory: true },
          { name: "Inspeção de arnês/fivelas", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "Roaring Forties",
    manufacturingCountry: "Austrália",
    summary: "Gama completa de coletes insufláveis para recreio, costeiro e offshore com modelos automáticos e manuais.",
    inflationSystems: ["automatic inflator", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["ISO 12402-3", "ISO 12402-2"],
    models: [
      {
        model: "Aviation",
        manufacturingCountry: "Austrália",
        family: "Aviação",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Aviação"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Colete específico para operações aéreas",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Force ISO9650 Type I",
        manufacturingCountry: "Austrália",
        family: "Costeiro",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 9650-1"],
        applications: ["Costeiro", "Embarcações pequenas"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Conformidade com ISO 9650 Tipo I",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Ocean Plus",
        manufacturingCountry: "Austrália",
        family: "Offshore",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Offshore", "Cruzeiro"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo offshore com características de segurança avançadas",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "ORL",
        manufacturingCountry: "Austrália",
        family: "Recreio leve",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Recreio", "Embarcações pequenas"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo compacto para recreio leve",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "USL Coastal",
        manufacturingCountry: "Austrália",
        family: "Costeiro",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Costeiro", "Navegação costeira"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo específico para navegação costeira",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "Seaman Safety",
    manufacturingCountry: "Turquia",
    summary: "Gama de coletes insufláveis profissionais e recreio da Seaman Safety com certificações internacionais.",
    inflationSystems: ["automatic inflator", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["SOLAS", "ISO 12402-3", "ISO 9650"],
    models: [
      {
        model: "DFN-D",
        manufacturingCountry: "Turquia",
        family: "Profissional",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["SOLAS", "ISO 12402-3"],
        applications: ["Profissional", "Navegação comercial"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo profissional com certificação SOLAS",
          "Construção robusta para operações contínuas",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "DFN-T",
        manufacturingCountry: "Turquia",
        family: "Profissional",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["SOLAS", "ISO 12402-3"],
        applications: ["Profissional", "Navegação comercial"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Variante de DFN com configuração alternativa",
          "Certificação SOLAS completa",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Seawolf ECE-T",
        manufacturingCountry: "Turquia",
        family: "Costeiro",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3", "ECE"],
        applications: ["Costeiro", "Embarcações comerciais"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Certificação ECE para navegação europeia",
          "Modelo costeiro profissional",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "Seawolf SDF",
        manufacturingCountry: "Turquia",
        family: "Offshore",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["ISO 12402-3"],
        applications: ["Offshore", "Navegação offshore"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo offshore com características avançadas",
          "Construção reforçada para condições severas",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "YJT",
        manufacturingCountry: "Turquia",
        family: "Profissional",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["SOLAS", "ISO 12402-3"],
        applications: ["Profissional", "Navegação comercial"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo profissional de segurança avançada",
          "Certificação múltipla SOLAS e ISO",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "YSR",
        manufacturingCountry: "Turquia",
        family: "Profissional",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["SOLAS", "ISO 12402-3"],
        applications: ["Profissional", "Resgate"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo de resgate profissional",
          "Características de estabilidade aprimoradas",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
      {
        model: "YT",
        manufacturingCountry: "Turquia",
        family: "Profissional",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático ou manual",
        certifications: ["SOLAS", "ISO 12402-3"],
        applications: ["Profissional", "Navegação comercial"],
        sizes: ["Adulto universal"],
        characteristics: [
          "Modelo compacto profissional",
          "Fácil armazenamento e manutenção",
        ],
        serviceItems: [
          { name: "Cilindro CO₂", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo", interval: "Anual", mandatory: true },
          { name: "Teste de estanquidade da câmara", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
  {
    brand: "TRIBOARD",
    manufacturingCountry: "França",
    summary: "Gama de coletes insufláveis Triboard (Decathlon) para vela e atividades náuticas, conhecidos pelos modelos ergonómicos LJ 150N com insuflador automático UML ou manual.",
    inflationSystems: ["UML automatic", "manual pull cord", "oral tube topping-up"],
    commonStandards: ["EN ISO 12402-3", "EN ISO 12402-7", "EN ISO 12402-8"],
    models: [
      {
        model: "LJ 150N",
        manufacturingCountry: "França",
        family: "Recreio / Vela",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Automático (UML) ou Manual",
        certifications: ["EN ISO 12402-3"],
        applications: ["Vela de cruzeiro", "Navegação costeira", "Atividades náuticas de recreio"],
        sizes: ["Peso mínimo 40 kg", "Peito 55-140 cm"],
        characteristics: [
          "Desenho plano e ergonómico para total liberdade de movimentos",
          "Insuflador UML com cilindro de CO₂ de 33g",
          "Variantes com e sem arnês integrado para segurança",
          "Tubo de sopro oral com válvula antirretorno",
          "Capa exterior resistente a abrasão com fecho de velcro ou zip de rutura rápida",
        ],
        serviceItems: [
          { name: "Cilindro CO₂ 33g", notes: "Verificar integridade e peso", interval: "Anual", mandatory: true },
          { name: "Pastilha de celulose (UML)", notes: "Substituir conforme data de validade ou se exposto à humidade", interval: "Anual", mandatory: true },
          { name: "Mecanismo de disparo automático UML", notes: "Verificar indicadores verde/vermelho de segurança", interval: "Anual", mandatory: true },
          { name: "Câmara de insuflação (Teste estanquidade)", notes: "Insuflar por 16 horas à pressão recomendada", interval: "Anual", mandatory: true },
          { name: "Apito de emergência", notes: "Verificar fixação e funcionamento", interval: "Anual", mandatory: false },
        ],
      },
      {
        model: "LJ 150N AIR",
        manufacturingCountry: "França",
        family: "Recreio / Vela",
        buoyancy: "150N",
        chamber: "Câmara simples",
        activation: "Manual",
        certifications: ["EN ISO 12402-3"],
        applications: ["Navegação costeira", "Pesca desportiva"],
        sizes: ["Adulto universal (peso > 40 kg)"],
        characteristics: [
          "Design clássico ultra-leve e de baixo perfil",
          "Ativação apenas por puxador manual ou tubo de sopro",
          "Tecido exterior em poliéster resistente",
        ],
        serviceItems: [
          { name: "Cilindro CO₂ 33g", notes: "Verificar peso", interval: "Anual", mandatory: true },
          { name: "Cilindro de acionamento manual", notes: "Verificar agulha de perfuração e alavanca", interval: "Anual", mandatory: true },
          { name: "Câmara de insuflação (Teste estanquidade)", notes: "Teste de 16h", interval: "Anual", mandatory: true },
        ],
      },
    ],
  },
];
