import { Prisma, PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config({ path: '.env' });
dotenv.config({ path: '.env.local' });

const connectionString =
  process.env.DIRECT_URL ??
  process.env.DATABASE_URL ??
  process.env.gestornavalpro_DATABASE_URL ??
  process.env.GESTOR_DB;

if (!connectionString) {
  console.error('No database connection string found. Set DIRECT_URL or DATABASE_URL in .env.local');
  process.exit(1);
}

const prisma = new PrismaClient({ datasources: { db: { url: connectionString } } });

type DbColumn = {
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: 'YES' | 'NO';
};

function mapScalarToSql(field: Prisma.DMMF.Field): string {
  if (field.kind === 'enum') return 'TEXT';

  switch (field.type) {
    case 'Int':
      return 'INTEGER';
    case 'BigInt':
      return 'BIGINT';
    case 'Float':
      return 'DOUBLE PRECISION';
    case 'Decimal':
      return 'NUMERIC';
    case 'Boolean':
      return 'BOOLEAN';
    case 'DateTime':
      return 'TIMESTAMP(3)';
    case 'Json':
      return 'JSONB';
    case 'Bytes':
      return 'BYTEA';
    case 'String':
    default:
      return 'TEXT';
  }
}

async function main() {
  const dbTables = (await prisma.$queryRaw`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  `) as Array<{ table_name: string }>;

  const dbColumns = (await prisma.$queryRaw`
    SELECT table_name, column_name, data_type, udt_name, is_nullable
    FROM information_schema.columns
    WHERE table_schema = 'public'
  `) as DbColumn[];

  const dbTableSet = new Set(dbTables.map((t) => t.table_name));
  const dbColumnsByTable = new Map<string, DbColumn[]>();
  for (const col of dbColumns) {
    const list = dbColumnsByTable.get(col.table_name) ?? [];
    list.push(col);
    dbColumnsByTable.set(col.table_name, list);
  }

  const models = Prisma.dmmf.datamodel.models;

  const report = {
    timestamp: new Date().toISOString(),
    dbTableCount: dbTables.length,
    prismaModelCount: models.length,
    missingTables: [] as Array<{ model: string; table: string }>,
    missingColumns: [] as Array<{
      model: string;
      table: string;
      field: string;
      column: string;
      type: string;
      optional: boolean;
      suggestedSql: string;
      caseInsensitiveMatch?: string;
    }>,
    extraDbColumns: [] as Array<{ table: string; column: string }>,
  };

  for (const model of models) {
    const tableName = model.dbName ?? model.name;
    const hasTable = dbTableSet.has(tableName);

    if (!hasTable) {
      report.missingTables.push({ model: model.name, table: tableName });
      continue;
    }

    const columns = dbColumnsByTable.get(tableName) ?? [];
    const columnSet = new Set(columns.map((c) => c.column_name));
    const columnSetLower = new Set(columns.map((c) => c.column_name.toLowerCase()));

    const scalarFields = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');

    for (const field of scalarFields) {
      const columnName = field.dbName ?? field.name;
      if (!columnSet.has(columnName)) {
        const lower = columnName.toLowerCase();
        const maybeCaseInsensitive = columnSetLower.has(lower)
          ? columns.find((c) => c.column_name.toLowerCase() === lower)?.column_name
          : undefined;

        const sqlType = mapScalarToSql(field);
        const nullability = field.isRequired ? 'NOT NULL' : 'NULL';
        const suggestedSql = `ALTER TABLE "${tableName}" ADD COLUMN "${columnName}" ${sqlType} ${nullability};`;

        report.missingColumns.push({
          model: model.name,
          table: tableName,
          field: field.name,
          column: columnName,
          type: `${field.kind}:${String(field.type)}`,
          optional: !field.isRequired,
          suggestedSql,
          caseInsensitiveMatch: maybeCaseInsensitive,
        });
      }
    }

    const expectedColumns = new Set(
      scalarFields.map((f) => f.dbName ?? f.name)
    );

    for (const dbCol of columns) {
      if (!expectedColumns.has(dbCol.column_name)) {
        report.extraDbColumns.push({ table: tableName, column: dbCol.column_name });
      }
    }
  }

  const outPath = path.join(process.cwd(), 'scripts', 'schema_drift_report.json');
  const sqlPath = path.join(process.cwd(), 'scripts', 'schema_drift_suggested_fix.sql');

  fs.writeFileSync(outPath, JSON.stringify(report, null, 2), 'utf8');

  const sqlLines = [
    '-- Suggested SQL generated by scripts/diagnose_schema_drift.ts',
    `-- Generated at ${new Date().toISOString()}`,
    '',
    ...report.missingColumns.map((item) => item.suggestedSql),
    '',
  ];
  fs.writeFileSync(sqlPath, sqlLines.join('\n'), 'utf8');

  console.log('Diagnóstico de schema drift concluído.');
  console.log(`Missing tables: ${report.missingTables.length}`);
  console.log(`Missing columns: ${report.missingColumns.length}`);
  console.log(`Extra DB columns: ${report.extraDbColumns.length}`);
  console.log(`Relatório: ${path.relative(process.cwd(), outPath)}`);
  console.log(`SQL sugerido: ${path.relative(process.cwd(), sqlPath)}`);
}

main()
  .catch((error) => {
    console.error('Erro no diagnóstico de schema drift:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
